# Generated by Django 6.1 on 2026-08-29 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.core.models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediaitem",
            name="file",
            field=models.FileField(upload_to=apps.core.models.owned_upload_path),
        ),
        migrations.AlterField(
            model_name="mediaitem",
            name="owner",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="mediaitem",
            index=models.Index(
                fields=["owner", "-created", "-id"],
                name="gallery_med_owner_i_c0a3ce_idx",
            ),
        ),
    ]
