# Generated by Django 6.1 on 2026-08-31 15:44

import django.db.models.deletion
import django.db.models.functions.datetime
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models

import apps.core.models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0002_alter_mediaitem_file_alter_mediaitem_owner_and_more"),
        ("pghistory", "0007_auto_20250421_0444"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaItemEvent",
            fields=[
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=models.Func(function="uuidv7"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pgh_schema", models.TextField(db_default="2026-08")),
                ("pgh_archive", models.JSONField(default=None, null=True)),
                (
                    "id",
                    models.UUIDField(
                        db_default=models.Func(function="uuidv7"),
                        editable=False,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("version", models.PositiveIntegerField(db_default=1, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(default=None, editable=False, null=True),
                ),
                (
                    "file",
                    models.FileField(upload_to=apps.core.models.owned_upload_path),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")], max_length=5
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=100)),
                ("size", models.PositiveBigIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="mediaitem",
            name="deleted_at",
            field=models.DateTimeField(db_index=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="mediaitem",
            name="version",
            field=models.PositiveIntegerField(db_default=1, editable=False),
        ),
        migrations.AlterField(
            model_name="mediaitem",
            name="created",
            field=models.DateTimeField(
                db_default=django.db.models.functions.datetime.Now(), editable=False
            ),
        ),
        migrations.AlterField(
            model_name="mediaitem",
            name="id",
            field=models.UUIDField(
                db_default=models.Func(function="uuidv7"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="mediaitem",
            name="modified",
            field=models.DateTimeField(
                db_default=django.db.models.functions.datetime.Now(), editable=False
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="mediaitem",
            trigger=pgtrigger.compiler.Trigger(
                name="no_hard_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot delete rows from % table', TG_TABLE_NAME;",
                    hash="17405002408507f6c1ab712c1c43cbc7e8dd2bb9",
                    operation="DELETE",
                    pgid="pgtrigger_no_hard_delete_8f86d",
                    table="gallery_mediaitem",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="mediaitem",
            trigger=pgtrigger.compiler.Trigger(
                name="bump_version",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="NEW.version = OLD.version + 1; NEW.modified = STATEMENT_TIMESTAMP(); RETURN NEW;",
                    hash="7a601da3e71e6c5c416187597cf7a18c80d7ca4e",
                    operation="UPDATE",
                    pgid="pgtrigger_bump_version_af4bc",
                    table="gallery_mediaitem",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="mediaitem",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "gallery_mediaitemevent" ("content_type", "created", "deleted_at", "file", "id", "kind", "modified", "name", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "size", "version") VALUES (NEW."content_type", NEW."created", NEW."deleted_at", NEW."file", NEW."id", NEW."kind", NEW."modified", NEW."name", NEW."owner_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."size", NEW."version"); RETURN NULL;',
                    hash="dd7d929a4aab5c0032ae9128f1738706e9b72a8b",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_494db",
                    table="gallery_mediaitem",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="mediaitem",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "gallery_mediaitemevent" ("content_type", "created", "deleted_at", "file", "id", "kind", "modified", "name", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "size", "version") VALUES (NEW."content_type", NEW."created", NEW."deleted_at", NEW."file", NEW."id", NEW."kind", NEW."modified", NEW."name", NEW."owner_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."size", NEW."version"); RETURN NULL;',
                    hash="d423bb7d69a9d9bde30ee21ade50ac7ba2745538",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_47a03",
                    table="gallery_mediaitem",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddField(
            model_name="mediaitemevent",
            name="owner",
            field=models.ForeignKey(
                db_constraint=False,
                editable=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mediaitemevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="mediaitemevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="gallery.mediaitem",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="mediaitemevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="24bf42aa24119e0f357e71456723c4beb955c68b",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_ad999",
                    table="gallery_mediaitemevent",
                    when="BEFORE",
                ),
            ),
        ),
    ]
