# Generated by Django 6.1 on 2026-09-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0006_mediaitemevent_pgh_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediaitemevent",
            name="pgh_schema",
            field=models.TextField(db_default="2026-09-02"),
        ),
    ]
