# Generated by Django 6.1 on 2026-09-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0007_alter_mediaitemevent_pgh_schema"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediaitemevent",
            name="pgh_schema",
            field=models.TextField(db_default="2026-09-02b"),
        ),
    ]
