# Generated by Django 6.1 on 2026-09-03 05:50

import django.db.models.deletion
import django.db.models.functions.comparison
import django.db.models.functions.datetime
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pghistory", "0007_auto_20250421_0444"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TimelineEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=models.Func(function="uuidv7"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("version", models.PositiveIntegerField(db_default=1, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(db_index=True, default=None, editable=False, null=True),
                ),
                ("event_type", models.CharField(db_index=True, max_length=100)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("technical", "Technical"),
                            ("real_world", "Real world"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suggested", "Suggested"),
                            ("rejected", "Rejected"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("occurred_until", models.DateTimeField(blank=True, null=True)),
                (
                    "date_precision",
                    models.CharField(
                        choices=[
                            ("datetime", "Date and time"),
                            ("day", "Day"),
                            ("month", "Month"),
                            ("year", "Year"),
                        ],
                        default="day",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("image_url", models.CharField(blank=True, default="", max_length=500)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("source_model", models.CharField(max_length=100)),
                ("source_id", models.UUIDField()),
                (
                    "owner",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "-id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TimelineEventEvent",
            fields=[
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=models.Func(function="uuidv7"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pgh_schema", models.TextField(db_default="2026-09-03")),
                ("pgh_archive", models.JSONField(default=None, null=True)),
                (
                    "pgh_stack",
                    models.JSONField(
                        db_default=django.db.models.functions.comparison.Cast(
                            django.db.models.functions.comparison.NullIf(
                                models.Func(
                                    models.Value("dx.stack"),
                                    models.Value(True),
                                    function="current_setting",
                                ),
                                models.Value(""),
                            ),
                            models.JSONField(),
                        ),
                        null=True,
                    ),
                ),
                (
                    "pgh_release",
                    models.TextField(
                        db_default=django.db.models.functions.comparison.Cast(
                            django.db.models.functions.comparison.NullIf(
                                models.Func(
                                    models.Value("dx.release"),
                                    models.Value(True),
                                    function="current_setting",
                                ),
                                models.Value(""),
                            ),
                            models.TextField(),
                        ),
                        null=True,
                    ),
                ),
                (
                    "pgh_request",
                    models.UUIDField(
                        db_default=django.db.models.functions.comparison.Cast(
                            django.db.models.functions.comparison.NullIf(
                                models.Func(
                                    models.Value("dx.request"),
                                    models.Value(True),
                                    function="current_setting",
                                ),
                                models.Value(""),
                            ),
                            models.UUIDField(),
                        ),
                        db_index=True,
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_default=models.Func(function="uuidv7"),
                        editable=False,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("version", models.PositiveIntegerField(db_default=1, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(default=None, editable=False, null=True),
                ),
                ("event_type", models.CharField(max_length=100)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("technical", "Technical"),
                            ("real_world", "Real world"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suggested", "Suggested"),
                            ("rejected", "Rejected"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("occurred_until", models.DateTimeField(blank=True, null=True)),
                (
                    "date_precision",
                    models.CharField(
                        choices=[
                            ("datetime", "Date and time"),
                            ("day", "Day"),
                            ("month", "Month"),
                            ("year", "Year"),
                        ],
                        default="day",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("image_url", models.CharField(blank=True, default="", max_length=500)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("source_model", models.CharField(max_length=100)),
                ("source_id", models.UUIDField()),
                (
                    "owner",
                    models.ForeignKey(
                        db_constraint=False,
                        editable=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pgh_context",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pghistory.context",
                    ),
                ),
                (
                    "pgh_obj",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="events",
                        to="timeline.timelineevent",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="timelineevent",
            index=models.Index(fields=["owner", "-occurred_at", "-id"], name="timeline_feed_idx"),
        ),
        migrations.AddIndex(
            model_name="timelineevent",
            index=models.Index(fields=["source_model", "source_id"], name="timeline_source_idx"),
        ),
        migrations.AddConstraint(
            model_name="timelineevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("source_model", "source_id", "event_type"),
                name="timeline_uniq_source_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="timelineevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("occurred_until__isnull", True),
                    ("occurred_until__gte", models.F("occurred_at")),
                    _connector="OR",
                ),
                name="timeline_range_valid",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="timelineevent",
            trigger=pgtrigger.compiler.Trigger(
                name="no_hard_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot delete rows from % table', TG_TABLE_NAME;",
                    hash="047a509d5d81b7060fc2846323a29a03639ce20f",
                    operation="DELETE",
                    pgid="pgtrigger_no_hard_delete_32212",
                    table="timeline_timelineevent",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="timelineevent",
            trigger=pgtrigger.compiler.Trigger(
                name="bump_version",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="NEW.version = OLD.version + 1; NEW.modified = STATEMENT_TIMESTAMP(); RETURN NEW;",
                    hash="b9b490c4a7c1ed79bbd3ed9eb588388fe16f47df",
                    operation="UPDATE",
                    pgid="pgtrigger_bump_version_bfe37",
                    table="timeline_timelineevent",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="timelineevent",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "timeline_timelineeventevent" ("created", "date_precision", "deleted_at", "description", "event_type", "id", "image_url", "kind", "modified", "occurred_at", "occurred_until", "owner_id", "payload", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "source_id", "source_model", "status", "title", "version") VALUES (NEW."created", NEW."date_precision", NEW."deleted_at", NEW."description", NEW."event_type", NEW."id", NEW."image_url", NEW."kind", NEW."modified", NEW."occurred_at", NEW."occurred_until", NEW."owner_id", NEW."payload", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."source_id", NEW."source_model", NEW."status", NEW."title", NEW."version"); RETURN NULL;',
                    hash="23f08491b661d03ee53d7c247d7984f1f7ea6893",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_68b77",
                    table="timeline_timelineevent",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="timelineevent",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "timeline_timelineeventevent" ("created", "date_precision", "deleted_at", "description", "event_type", "id", "image_url", "kind", "modified", "occurred_at", "occurred_until", "owner_id", "payload", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "source_id", "source_model", "status", "title", "version") VALUES (NEW."created", NEW."date_precision", NEW."deleted_at", NEW."description", NEW."event_type", NEW."id", NEW."image_url", NEW."kind", NEW."modified", NEW."occurred_at", NEW."occurred_until", NEW."owner_id", NEW."payload", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."source_id", NEW."source_model", NEW."status", NEW."title", NEW."version"); RETURN NULL;',
                    hash="68c4f5e882b467df44d6a695cad280326d68ab76",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_ac358",
                    table="timeline_timelineevent",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="timelineeventevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="1c4223476cf2e97e044fbced72d3d92cebd245b6",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_0e3ac",
                    table="timeline_timelineeventevent",
                    when="BEFORE",
                ),
            ),
        ),
    ]
