# Mini-stub for pypdfium2 (no py.typed upstream; NOTES.md §5: own stubs instead of
# ignore_missing_imports). Only what `manage.py playground render` uses.
from collections.abc import Iterator
from os import PathLike

from PIL.Image import Image

class PdfBitmap:
    def to_pil(self) -> Image: ...
    def close(self) -> None: ...

class PdfPage:
    def get_size(self) -> tuple[float, float]: ...
    def render(self, scale: float = 1, rotation: int = 0) -> PdfBitmap: ...
    def close(self) -> None: ...

class PdfDocument:
    def __init__(
        self,
        input: str | PathLike[str] | bytes,
        password: str | None = None,
        autoclose: bool = False,
    ) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> PdfPage: ...
    def __iter__(self) -> Iterator[PdfPage]: ...
    def close(self) -> None: ...
