# Generated by Django 6.1 on 2026-09-03 06:34

import django.db.models.deletion
import django.db.models.functions.comparison
import django.db.models.functions.datetime
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pghistory", "0007_auto_20250421_0444"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=models.Func(function="uuidv7"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("version", models.PositiveIntegerField(db_default=1, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(db_index=True, default=None, editable=False, null=True),
                ),
                ("notification_type", models.CharField(db_index=True, max_length=100)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("source_model", models.CharField(max_length=100)),
                ("source_id", models.UUIDField()),
                ("read_at", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created", "-id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NotificationEvent",
            fields=[
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=models.Func(function="uuidv7"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pgh_schema", models.TextField(db_default="2026-09-03")),
                ("pgh_archive", models.JSONField(default=None, null=True)),
                (
                    "pgh_stack",
                    models.JSONField(
                        db_default=django.db.models.functions.comparison.Cast(
                            django.db.models.functions.comparison.NullIf(
                                models.Func(
                                    models.Value("dx.stack"),
                                    models.Value(True),
                                    function="current_setting",
                                ),
                                models.Value(""),
                            ),
                            models.JSONField(),
                        ),
                        null=True,
                    ),
                ),
                (
                    "pgh_release",
                    models.TextField(
                        db_default=django.db.models.functions.comparison.Cast(
                            django.db.models.functions.comparison.NullIf(
                                models.Func(
                                    models.Value("dx.release"),
                                    models.Value(True),
                                    function="current_setting",
                                ),
                                models.Value(""),
                            ),
                            models.TextField(),
                        ),
                        null=True,
                    ),
                ),
                (
                    "pgh_request",
                    models.UUIDField(
                        db_default=django.db.models.functions.comparison.Cast(
                            django.db.models.functions.comparison.NullIf(
                                models.Func(
                                    models.Value("dx.request"),
                                    models.Value(True),
                                    function="current_setting",
                                ),
                                models.Value(""),
                            ),
                            models.UUIDField(),
                        ),
                        db_index=True,
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_default=models.Func(function="uuidv7"),
                        editable=False,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("version", models.PositiveIntegerField(db_default=1, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(default=None, editable=False, null=True),
                ),
                ("notification_type", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("source_model", models.CharField(max_length=100)),
                ("source_id", models.UUIDField()),
                ("read_at", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        db_constraint=False,
                        editable=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pgh_context",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pghistory.context",
                    ),
                ),
                (
                    "pgh_obj",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="events",
                        to="notifications.notification",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["owner", "read_at", "-created", "-id"],
                name="notification_inbox_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["source_model", "source_id"], name="notification_source_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("source_model", "source_id", "notification_type"),
                name="notification_uniq_source_type",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="notification",
            trigger=pgtrigger.compiler.Trigger(
                name="no_hard_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot delete rows from % table', TG_TABLE_NAME;",
                    hash="a7d56e4cc4e3e4b0721cec4a8754f4909bfbcaec",
                    operation="DELETE",
                    pgid="pgtrigger_no_hard_delete_3d262",
                    table="notifications_notification",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="notification",
            trigger=pgtrigger.compiler.Trigger(
                name="bump_version",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="NEW.version = OLD.version + 1; NEW.modified = STATEMENT_TIMESTAMP(); RETURN NEW;",
                    hash="d2bbbe396dd6d46e537bdaba103e793da8809aa2",
                    operation="UPDATE",
                    pgid="pgtrigger_bump_version_8de07",
                    table="notifications_notification",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="notification",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "notifications_notificationevent" ("created", "deleted_at", "description", "id", "modified", "notification_type", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "read_at", "source_id", "source_model", "title", "version") VALUES (NEW."created", NEW."deleted_at", NEW."description", NEW."id", NEW."modified", NEW."notification_type", NEW."owner_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."read_at", NEW."source_id", NEW."source_model", NEW."title", NEW."version"); RETURN NULL;',
                    hash="42f755b0b57fbcb28003851269bb9f2fd828fd70",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_e1b01",
                    table="notifications_notification",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="notification",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "notifications_notificationevent" ("created", "deleted_at", "description", "id", "modified", "notification_type", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "read_at", "source_id", "source_model", "title", "version") VALUES (NEW."created", NEW."deleted_at", NEW."description", NEW."id", NEW."modified", NEW."notification_type", NEW."owner_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."read_at", NEW."source_id", NEW."source_model", NEW."title", NEW."version"); RETURN NULL;',
                    hash="045df83cecbccb8eb4ed5334ff46b1213021e297",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_a25db",
                    table="notifications_notification",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="notificationevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="1947c96fb2549341bb7e1736d88b1b5a8d4b2f4a",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_3b683",
                    table="notifications_notificationevent",
                    when="BEFORE",
                ),
            ),
        ),
    ]
