# Generated by Django 6.1 on 2026-09-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationevent",
            name="pgh_schema",
            field=models.TextField(db_default="2026-09-03b"),
        ),
    ]
