"""Every model hands out one saveable example of itself (`apps/core/examples.py`).

The first two tests are the contract, and they are what `manage.py check_examples` runs as well
— here against the test database as part of the suite, there against a real one. The rest is
`save_example`'s own behaviour: the tenant column it fills in and the rows it saves before the
row it was given.
"""

from pathlib import Path

import pytest
from django.contrib.contenttypes.models import ContentType
from pytest_django.fixtures import Settings

from apps.accounts.models import User
from apps.core.db import NoTenantContext
from apps.core.examples import (
    example_models,
    example_of,
    models_without_example,
    save_example,
    unique,
    unsaveable_examples,
)
from apps.core.testing import acting_as
from apps.datasets.models import Dataset, DatasetTag, Tag
from apps.notes.models import Note

pytestmark = pytest.mark.django_db


@pytest.fixture(autouse=True)
def media_root(settings: Settings, tmp_path: Path) -> None:
    """The examples with a `FileField` really write their file; keep it out of the media store."""
    settings.MEDIA_ROOT = tmp_path


def test_every_model_defines_its_own_example() -> None:
    assert models_without_example() == []


def test_every_example_saves() -> None:
    assert unsaveable_examples() == []


def test_example_models_are_this_projects_models() -> None:
    labels = [model._meta.label for model in example_models()]

    assert {"accounts.User", "core.Lineage", "datasets.Dataset"} <= set(labels)
    # Generated by @tracked and written by a trigger: append-only, never built by hand.
    assert "datasets.DatasetEvent" not in labels
    # Third-party tables are not ours to give an example to.
    assert "contenttypes.ContentType" not in labels


def test_save_example_fills_in_the_owner(user: User) -> None:
    with acting_as(user):
        dataset = save_example(Dataset.example())

        assert dataset.pk is not None
        assert dataset.owner_id == user.pk
        assert dataset.version == 1  # a normal, versioned insert
        assert list(Dataset.objects.for_user(user)) == [dataset]


def test_save_example_saves_what_the_example_points_at(user: User) -> None:
    with acting_as(user):
        link = save_example(DatasetTag.example())

        assert Dataset.objects.for_user(user).get() == link.dataset  # written before the link
        assert Tag.objects.for_user(user).get() == link.tag
        assert link.dataset.tag_names() == [link.tag.name]


def test_two_examples_of_the_same_model_can_be_saved(user: User) -> None:
    """`unique()` on a field under a unique constraint — the collision would be the first thing
    anyone writing a second one hits."""
    with acting_as(user):
        first, second = save_example(Tag.example()), save_example(Tag.example())

    assert first.name != second.name


def test_an_owned_example_needs_a_tenant_context(db: None) -> None:
    with pytest.raises(NoTenantContext):
        save_example(Note.example())


def test_a_shared_model_saves_without_a_tenant_context(db: None) -> None:
    """`accounts.User` has no owner column, so there is no tenant to act as."""
    assert save_example(User.example()).pk is not None


def test_example_of_rejects_a_model_without_one() -> None:
    with pytest.raises(TypeError, match="no example"):
        example_of(ContentType)


def test_unique_keeps_the_text_it_is_given() -> None:
    assert unique("finance").startswith("finance-")
