/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */

export interface ApiTokenOut {
  created: string;
  id: string;
  last_used: string | null;
  /**
   * What the token is used for
   * @maxLength 255
   */
  name: string;
  /** @maxLength 64 */
  token?: string;
}
