/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Additive summary of per-word confidences: `{n, sum, min, max, hist[10]}`.
 *
 * Ten uniform buckets over [0, 1], the last one right-inclusive. Merging two summaries is
 * elementwise addition (plus min/max), which is what lets every level of the snapshot carry
 * one — region, node subtree, page, content — computed once, bottom-up, at write time. The
 * reader picks the measure: `mean`, the histogram, or the exact words of one region.
 *
 * `None` in a `conf_stats` column means "no OCR happened here" (born-digital input). Never a
 * fake 1.0.
 */
export interface ConfStats {
  /**
   * @minItems 10
   * @maxItems 10
   */
  hist: number[];
  max: number;
  min: number;
  /** @minimum 1 */
  n: number;
  sum: number;
}
