/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */
import type { ConfStats } from "./confStats";
import type { ContentOutMeta } from "./contentOutMeta";
import type { DateOut } from "./dateOut";
import type { ExtractionOut } from "./extractionOut";
import type { ExtractionStatus } from "./extractionStatus";
import type { OutlineEntryOut } from "./outlineEntryOut";

/**
 * The facade in one response: what the current snapshot says, plus the latest run.
 */
export interface ContentOut {
  confidence: ConfStats | null;
  date: DateOut | null;
  extraction: ExtractionOut | null;
  html: string;
  meta: ContentOutMeta;
  outline: OutlineEntryOut[];
  page_count: number;
  resumable_pages: number;
  status: ExtractionStatus | null;
  text: string;
}
