/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */

export interface CountIn {
  /**
   * Seconds per step
   * @minimum 0
   * @maximum 10
   */
  delay?: number;
  /**
   * @minimum 1
   * @maximum 600
   */
  n?: number;
}
