/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */
import type { DatasetOptions } from "./datasetOptions";

/**
 * Create (POST) and full update (PUT): every field, omitted ones take the defaults.
 */
export interface DatasetIn {
  description?: string;
  /**
   * @minLength 1
   * @maxLength 200
   */
  name: string;
  options?: DatasetOptions;
  /** @minimum 0 */
  row_count?: number;
  /** @maxItems 25 */
  tags?: string[];
}
