/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */
import type { DatasetOptions } from "./datasetOptions";

export interface DatasetOut {
  created: string;
  description: string;
  id: string;
  modified: string;
  /** @maxLength 200 */
  name: string;
  options: DatasetOptions;
  row_count: number;
}
