/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */
import type { DatasetOptions } from "./datasetOptions";

/**
 * Partial update (PATCH): only the fields that are present change.
 */
export interface DatasetPatch {
  description?: string | null;
  name?: string | null;
  options?: DatasetOptions | null;
  row_count?: number | null;
  tags?: string[] | null;
}
