/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Import settings of a dataset — a typed JSON column (django-pydantic-field, NOTES.md §5).
 *
 * Stored as `jsonb`, validated on load and save, and part of the API contract (nested object
 * in `DatasetOut`/`DatasetIn`, so the frontend gets a typed `DatasetOptions` as well).
 * Evolve it like any pydantic model: new fields need a default so old rows still load.
 */
export interface DatasetOptions {
  /**
   * @minLength 1
   * @maxLength 1
   */
  delimiter?: string;
  encoding?: string;
  has_header?: boolean;
}
