/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */

/**
 * How a row's date is known — a column, because review queues filter on it.
 */
export type DateSource = (typeof DateSource)[keyof typeof DateSource];

export const DateSource = {
  explicit: "explicit",
  metadata: "metadata",
  inferred: "inferred",
  interpolated: "interpolated",
  inherited: "inherited",
  aggregated: "aggregated",
  curated: "curated",
} as const;
