/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */
import type { DateSource } from "./dateSource";

/**
 * From when the content originates (`apps/documents/dating.py`): the EDTF truth, its
 * strict bounds (null = unknown on that side), how it is known, how sure — and `display`
 * for a person: "May 12–20, 1943 (interpolated, 0.60)".
 */
export interface DateOut {
  conf: number | null;
  display: string;
  edtf: string;
  max: string | null;
  min: string | null;
  source: DateSource;
}
