/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */
import type { DateOut } from "./dateOut";
import type { DocumentOutMeta } from "./documentOutMeta";
import type { ExtractionStatus } from "./extractionStatus";

export interface DocumentOut {
  created: string;
  date: DateOut | null;
  download_url: string;
  id: string;
  meta: DocumentOutMeta;
  mime_type: string;
  modified: string;
  page_count: number;
  size: number;
  status: ExtractionStatus | null;
  thumb_url: string | null;
  title: string;
  version: number;
  view_url: string;
}
