/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */
import type { ConfStats } from "./confStats";
import type { DateOut } from "./dateOut";

/**
 * A node of the current snapshot, as the facade hands it out (`node_out`).
 */
export interface DocumentNodeOut {
  confidence: ConfStats | null;
  date: DateOut | null;
  html: string;
  level: number | null;
  nid: number;
  pages: number[];
  path: string;
  tag: string;
  text: string;
  text_end: number;
  text_start: number;
  title: string | null;
}
