/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */

export interface DocumentOut {
  content_type: string;
  created: string;
  download_url: string;
  id: string;
  /** @maxLength 255 */
  name: string;
  size: number;
}
