/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */
import type { DocumentPatchMeta } from "./documentPatchMeta";

export interface DocumentPatch {
  meta?: DocumentPatchMeta;
  title?: string | null;
}
