/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */
import type { ExtractionOutStats } from "./extractionOutStats";
import type { ExtractionStatus } from "./extractionStatus";

/**
 * One extraction run — process state, never the snapshot's rows (`extraction_out`).
 */
export interface ExtractionOut {
  created: string;
  error: string;
  extractor: string;
  finished_at: string | null;
  id: string;
  is_current: boolean;
  stale: boolean;
  started_at: string | null;
  stats: ExtractionOutStats;
  status: ExtractionStatus;
  /** Signed SSE endpoint of the run's task (`GET /api/tasks/{id}/events`): one `status` event per state change, with the page count while it works. */
  stream_url: string;
}
