/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */
import type { DateSource } from "./dateSource";

export type GetDocumentTimelineParams = {
  source?: DateSource | null;
  max_conf?: number | null;
};
