/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */
import type { EdgeOut } from "./edgeOut";
import type { NodeOut } from "./nodeOut";

export interface GraphOut {
  edges: EdgeOut[];
  nodes: NodeOut[];
  root_id: string;
}
