/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */

export const HealthOutValue = {
  status: "ok",
} as const;
export type HealthOut = typeof HealthOutValue;
