/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */
import type { RevisionGroupOut } from "./revisionGroupOut";

export interface HistoryOut {
  current_version: number;
  groups: RevisionGroupOut[];
  model: string;
  object_id: string;
}
