/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */
import type { DatasetOptions } from "./datasetOptions";

/**
 * Build a dataset from an uploaded document (`POST /api/datasets/import-document`).
 */
export interface ImportDatasetIn {
  document_id: string;
  name?: string | null;
  options?: DatasetOptions;
  /** @maxItems 25 */
  tags?: string[];
}
