/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */

export type ListDocumentsParams = {
  /**
   * @minimum 1
   */
  page?: number;
  page_size?: number | null;
};
