/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Join several notes into a new one (`POST /api/notes/merge`).
 */
export interface MergeNotesIn {
  /**
   * @minItems 2
   * @maxItems 20
   */
  note_ids: string[];
  /**
   * @minLength 1
   * @maxLength 200
   */
  title: string;
}
