/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */

/**
 * One object in the graph — the live row, not a version of it.
 */
export interface NodeOut {
  deleted: boolean;
  /** Steps from the object asked about: negative upstream (what it came from), positive downstream (what came from it) */
  depth: number;
  label: string;
  model: string;
  object_id: string;
  version: number;
}
