/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Partial update (PATCH): only the fields that are present change.
 */
export interface NotePatch {
  body?: string | null;
  tags?: string | null;
  title?: string | null;
}
