/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Create (POST) and full update (PUT).
 */
export interface NoteIn {
  body?: string;
  /** @maxLength 500 */
  tags?: string;
  /**
   * @minLength 1
   * @maxLength 200
   */
  title: string;
}
