/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */

export interface OutlineEntryOut {
  level: number | null;
  nid: number;
  tag: string;
  title: string;
}
