/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */
import type { DatasetOut } from "./datasetOut";

export interface PagedDatasetOut {
  count: number;
  items: DatasetOut[];
}
