/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */
import type { ConfStats } from "./confStats";
import type { DateOut } from "./dateOut";
import type { RegionOut } from "./regionOut";

export interface PageOut {
  confidence: ConfStats | null;
  date: DateOut | null;
  failed: boolean;
  height: number | null;
  html: string;
  image_url: string;
  label: string | null;
  number: number;
  regions: RegionOut[];
  text: string;
  thumb_url: string;
  width: number | null;
}
