/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */
import type { MediaItemOut } from "./mediaItemOut";

export interface PagedMediaItemOut {
  count: number;
  items: MediaItemOut[];
}
