/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */
import type { DocumentOut } from "./documentOut";

export interface PagedDocumentOut {
  count: number;
  items: DocumentOut[];
}
