/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */

export type ReadyOutStatus =
  (typeof ReadyOutStatus)[keyof typeof ReadyOutStatus];

export const ReadyOutStatus = {
  ok: "ok",
  fail: "fail",
} as const;
