/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */
import type { CheckOut } from "./checkOut";
import type { ReadyOutStatus } from "./readyOutStatus";

export interface ReadyOut {
  checks: CheckOut[];
  status: ReadyOutStatus;
}
