/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */

export interface RegisterIn {
  email?: string;
  first_name?: string;
  last_name?: string;
  /** @minLength 8 */
  password: string;
  /**
   * @minLength 1
   * @maxLength 150
   */
  username: string;
}
