/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */

export interface RegionOut {
  nid: number;
  order: number;
  polygon: number[][] | null;
  tag: string;
  text: string;
  x0: number;
  x1: number;
  y0: number;
  y1: number;
}
