/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */
import type { ChangeOut } from "./changeOut";
import type { RevisionOutArchived } from "./revisionOutArchived";
import type { SourceOut } from "./sourceOut";

export interface RevisionOut {
  /** Values of fields dropped since (pgh_archive) */
  archived: RevisionOutArchived;
  at: string;
  changes: ChangeOut[];
  context_id: string | null;
  deleted: boolean;
  /** What a child row points at, in words */
  description: string;
  /** A child row written in the same save (an explicit m2m through model, say) rather than a version of the object itself */
  is_related: boolean;
  label: string;
  model: string;
  object_id: string;
  pgh_id: string;
  /** False when the row predates the recorded field sets: its values cannot be diffed reliably (apps/core/history.py, SCHEMA_TAG) */
  schema_known: boolean;
  schema_tag: string;
  sources: SourceOut[];
  /** Fields not tracked at both ends of the comparison — not a change */
  unknown_fields: string[];
  version: number;
}
