/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */
import type { RevisionOut } from "./revisionOut";

/**
 * One save: everything a single request or task wrote, however many tables it touched.
 */
export interface RevisionGroupOut {
  at: string;
  context_id: string | null;
  revisions: RevisionOut[];
  source: string;
}
