/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Values of fields dropped since (pgh_archive)
 */
export type RevisionOutArchived = { [key: string]: string };
