/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */

/**
 * A lineage edge: the exact source *version* this revision was built from.
 */
export interface SourceOut {
  /** The source has been changed since this was derived */
  is_stale: boolean;
  label: string;
  model: string;
  object_id: string;
  pgh_id: string;
  version: number;
}
