/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */

export type TaskOutState = (typeof TaskOutState)[keyof typeof TaskOutState];

export const TaskOutState = {
  PENDING: "PENDING",
  RECEIVED: "RECEIVED",
  STARTED: "STARTED",
  PROGRESS: "PROGRESS",
  RETRY: "RETRY",
  SUCCESS: "SUCCESS",
  FAILURE: "FAILURE",
  REVOKED: "REVOKED",
  REJECTED: "REJECTED",
  IGNORED: "IGNORED",
} as const;
