/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */
import type { TaskOutState } from "./taskOutState";
import type { TaskProgress } from "./taskProgress";

/**
 * Snapshot of a Celery task. Until `ready` is true, follow it via `stream_url`
 * (Server-Sent Events) or poll `GET /api/tasks/{id}`.
 */
export interface TaskOut {
  error?: string | null;
  id: string;
  progress?: TaskProgress | null;
  ready: boolean;
  /** Return value once SUCCESS */
  result?: unknown | null;
  state: TaskOutState;
  /** Signed SSE endpoint: one `status` event (this schema) per state change */
  stream_url: string;
}
