/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */
import type { DateOut } from "./dateOut";

/**
 * A dated node of the current snapshot — `Document.timeline()`, one row each.
 */
export interface TimelineEntryOut {
  date: DateOut;
  excerpt: string;
  nid: number;
  pages: number[];
  tag: string;
}
