/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Send as `Authorization: Bearer <access_token>`.
 */
export interface TokenOut {
  access_token: string;
}
