/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */

export interface UserOut {
  email: string;
  first_name: string;
  id: string;
  is_staff: boolean;
  last_name: string;
  username: string;
}
