# Generated by Django 6.1 on 2026-08-31 15:44

import django.db.models.functions.datetime
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_refreshtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="apitoken",
            name="deleted_at",
            field=models.DateTimeField(db_index=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="apitoken",
            name="version",
            field=models.PositiveIntegerField(db_default=1, editable=False),
        ),
        migrations.AddField(
            model_name="refreshtoken",
            name="deleted_at",
            field=models.DateTimeField(db_index=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="refreshtoken",
            name="version",
            field=models.PositiveIntegerField(db_default=1, editable=False),
        ),
        migrations.AlterField(
            model_name="apitoken",
            name="created",
            field=models.DateTimeField(
                db_default=django.db.models.functions.datetime.Now(), editable=False
            ),
        ),
        migrations.AlterField(
            model_name="apitoken",
            name="id",
            field=models.UUIDField(
                db_default=models.Func(function="uuidv7"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="apitoken",
            name="modified",
            field=models.DateTimeField(
                db_default=django.db.models.functions.datetime.Now(), editable=False
            ),
        ),
        migrations.AlterField(
            model_name="refreshtoken",
            name="created",
            field=models.DateTimeField(
                db_default=django.db.models.functions.datetime.Now(), editable=False
            ),
        ),
        migrations.AlterField(
            model_name="refreshtoken",
            name="id",
            field=models.UUIDField(
                db_default=models.Func(function="uuidv7"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="refreshtoken",
            name="modified",
            field=models.DateTimeField(
                db_default=django.db.models.functions.datetime.Now(), editable=False
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apitoken",
            trigger=pgtrigger.compiler.Trigger(
                name="no_hard_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot delete rows from % table', TG_TABLE_NAME;",
                    hash="7dd30749adb1a7a9955d5cd004b9577675898bfd",
                    operation="DELETE",
                    pgid="pgtrigger_no_hard_delete_ed552",
                    table="accounts_apitoken",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apitoken",
            trigger=pgtrigger.compiler.Trigger(
                name="bump_version",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="NEW.version = OLD.version + 1; NEW.modified = STATEMENT_TIMESTAMP(); RETURN NEW;",
                    hash="cc6447a9bdc1f42603256a8654fb48ddec6c8e79",
                    operation="UPDATE",
                    pgid="pgtrigger_bump_version_b9457",
                    table="accounts_apitoken",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="refreshtoken",
            trigger=pgtrigger.compiler.Trigger(
                name="no_hard_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot delete rows from % table', TG_TABLE_NAME;",
                    hash="197e6512da7d705c8965b3408abf13e085acf477",
                    operation="DELETE",
                    pgid="pgtrigger_no_hard_delete_4a85e",
                    table="accounts_refreshtoken",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="refreshtoken",
            trigger=pgtrigger.compiler.Trigger(
                name="bump_version",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="NEW.version = OLD.version + 1; NEW.modified = STATEMENT_TIMESTAMP(); RETURN NEW;",
                    hash="da1b363acc6d9363faf02f55ae10bdb5285b3f70",
                    operation="UPDATE",
                    pgid="pgtrigger_bump_version_071a5",
                    table="accounts_refreshtoken",
                    when="BEFORE",
                ),
            ),
        ),
    ]
