# Generated by Django 6.1 on 2026-08-31 15:47

from django.db import migrations, models

import apps.accounts.models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_apitoken_deleted_at_apitoken_version_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apitoken",
            name="token",
            field=models.CharField(
                default=apps.accounts.models.generate_token,
                editable=False,
                max_length=64,
            ),
        ),
        migrations.AddConstraint(
            model_name="apitoken",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("token",),
                name="uniq_active_api_token",
            ),
        ),
    ]
