/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * Every version of one object, newest first, grouped into the saves that produced them.
 *
 * `resource` is the model name in lower case (`dataset`, `document`, `mediaitem`); the tracked
 * models are the ones with history (`apps/core/history.py`). Another tenant's object is a 404,
 * like everywhere else — the event tables carry the same row-level security policy.
 * @summary Get History
 */
export const GetHistoryParams = zod.object({
  resource: zod.string(),
  object_id: zod.uuid(),
});

export const GetHistoryResponse = zod.object({
  current_version: zod.int(),
  groups: zod.array(
    zod
      .object({
        at: zod.iso.datetime({ offset: true }),
        context_id: zod.union([zod.uuid(), zod.null()]),
        revisions: zod.array(
          zod.object({
            archived: zod
              .record(zod.string(), zod.string())
              .describe("Values of fields dropped since (pgh_archive)"),
            at: zod.iso.datetime({ offset: true }),
            changes: zod.array(
              zod.object({
                field: zod.string(),
                "new": zod.union([zod.string(), zod.null()]),
                old: zod.union([zod.string(), zod.null()]),
              }),
            ),
            context_id: zod.union([zod.uuid(), zod.null()]),
            deleted: zod.boolean(),
            description: zod
              .string()
              .describe("What a child row points at, in words"),
            is_related: zod
              .boolean()
              .describe(
                "A child row written in the same save (an explicit m2m through model, say) rather than a version of the object itself",
              ),
            label: zod.string(),
            model: zod.string(),
            object_id: zod.uuid(),
            pgh_id: zod.uuid(),
            schema_known: zod
              .boolean()
              .describe(
                "False when the row predates the recorded field sets: its values cannot be diffed reliably (apps\/core\/history.py, SCHEMA_TAG)",
              ),
            schema_tag: zod.string(),
            sources: zod.array(
              zod
                .object({
                  is_stale: zod
                    .boolean()
                    .describe(
                      "The source has been changed since this was derived",
                    ),
                  label: zod.string(),
                  model: zod.string(),
                  object_id: zod.uuid(),
                  pgh_id: zod.uuid(),
                  version: zod.int(),
                })
                .describe(
                  "A lineage edge: the exact source \*version\* this revision was built from.",
                ),
            ),
            unknown_fields: zod
              .array(zod.string())
              .describe(
                "Fields not tracked at both ends of the comparison — not a change",
              ),
            version: zod.int(),
          }),
        ),
        source: zod.string(),
      })
      .describe(
        "One save: everything a single request or task wrote, however many tables it touched.",
      ),
  ),
  model: zod.string(),
  object_id: zod.uuid(),
});

/**
 * What this object was built from and what was built from it, transitively.
 *
 * `resource` is the model name in lower case, as for the revision history. Edges point at a
 * *version* of a source, so an edge marked `is_stale` says the source has moved on since —
 * the derived object was built from something that no longer reads that way.
 * @summary Get Lineage
 */
export const GetLineageParams = zod.object({
  resource: zod.string(),
  object_id: zod.uuid(),
});

export const getLineageQueryDepthDefault = 3;

export const GetLineageQueryParams = zod.object({
  depth: zod.int().default(getLineageQueryDepthDefault),
});

export const GetLineageResponse = zod.object({
  edges: zod.array(
    zod.object({
      created: zod.iso.datetime({ offset: true }),
      is_stale: zod
        .boolean()
        .describe("The source has changed since this edge was recorded"),
      source_id: zod.uuid(),
      source_version: zod.int(),
      target_id: zod.uuid(),
    }),
  ),
  nodes: zod.array(
    zod
      .object({
        deleted: zod.boolean(),
        depth: zod
          .int()
          .describe(
            "Steps from the object asked about: negative upstream (what it came from), positive downstream (what came from it)",
          ),
        label: zod.string(),
        model: zod.string(),
        object_id: zod.uuid(),
        version: zod.int(),
      })
      .describe("One object in the graph — the live row, not a version of it."),
  ),
  root_id: zod.uuid(),
});
