# Generated by Django 4.2.12 on 2024-11-06 06:20

import django.utils.timezone
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.models.id_gen,
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                ("modified", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("done", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created"],
                "abstract": False,
            },
        ),
    ]
