# Generated by Django 5.2.6 on 2025-11-07 09:25

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_apitoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitoken',
            name='token',
            field=models.CharField(default=core.models.generate_token, max_length=50, unique=True),
        ),
    ]
