/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */

import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";
import { customFetch } from "../../lib/custom-fetch";
import type {
  ApiTokenIn,
  ApiTokenOut,
  LoginIn,
  RegisterIn,
  TokenOut,
  UserOut,
} from "../model";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getListApiTokensUrl = () => {
  return `/api/auth/api-tokens`;
};

/**
 * @summary List Api Tokens
 */
export const listApiTokens = async (
  options?: Parameters<typeof customFetch>[1],
): Promise<ApiTokenOut[]> => {
  return customFetch<ApiTokenOut[]>(getListApiTokensUrl(), {
    ...options,
    method: "GET",
  });
};

export const getListApiTokensQueryKey = () => {
  return [`/api/auth/api-tokens`] as const;
};

export const getListApiTokensQueryOptions = <
  TData = Awaited<ReturnType<typeof listApiTokens>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listApiTokens>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListApiTokensQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listApiTokens>>> = ({
    signal,
  }) => listApiTokens({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listApiTokens>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListApiTokensQueryResult = NonNullable<
  Awaited<ReturnType<typeof listApiTokens>>
>;
export type ListApiTokensQueryError = unknown;

/**
 * @summary List Api Tokens
 */

export function useListApiTokens<
  TData = Awaited<ReturnType<typeof listApiTokens>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listApiTokens>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListApiTokensQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getCreateApiTokenUrl = () => {
  return `/api/auth/api-tokens`;
};

/**
 * @summary Create Api Token
 */
export const createApiToken = async (
  apiTokenIn: ApiTokenIn,
  options?: Parameters<typeof customFetch>[1],
): Promise<ApiTokenOut> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
  return customFetch<ApiTokenOut>(getCreateApiTokenUrl(), {
    ...options,
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...getHeaders(options?.headers),
    },
    body: JSON.stringify(apiTokenIn),
  });
};

export const getCreateApiTokenMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createApiToken>>,
    TError,
    CreateApiTokenMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createApiToken>>,
  TError,
  CreateApiTokenMutationVariables,
  TContext
> => {
  const mutationKey = ["createApiToken"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createApiToken>>,
    CreateApiTokenMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return createApiToken(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateApiTokenMutationResult = NonNullable<
  Awaited<ReturnType<typeof createApiToken>>
>;
export type CreateApiTokenMutationBody = ApiTokenIn;
export type CreateApiTokenMutationError = unknown;
export type CreateApiTokenMutationVariables = { data: ApiTokenIn };

/**
 * @summary Create Api Token
 */
export const useCreateApiToken = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createApiToken>>,
    TError,
    CreateApiTokenMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createApiToken>>,
  TError,
  CreateApiTokenMutationVariables,
  TContext
> => {
  return useMutation(getCreateApiTokenMutationOptions(options));
};
export const getRevokeApiTokenUrl = (tokenId: string) => {
  return `/api/auth/api-tokens/${tokenId}`;
};

/**
 * @summary Revoke Api Token
 */
export const revokeApiToken = async (
  tokenId: string,
  options?: Parameters<typeof customFetch>[1],
): Promise<void> => {
  return customFetch<void>(getRevokeApiTokenUrl(tokenId), {
    ...options,
    method: "DELETE",
  });
};

export const getRevokeApiTokenMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof revokeApiToken>>,
    TError,
    RevokeApiTokenMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof revokeApiToken>>,
  TError,
  RevokeApiTokenMutationVariables,
  TContext
> => {
  const mutationKey = ["revokeApiToken"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof revokeApiToken>>,
    RevokeApiTokenMutationVariables
  > = (props) => {
    const { tokenId } = props ?? {};

    return revokeApiToken(tokenId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RevokeApiTokenMutationResult = NonNullable<
  Awaited<ReturnType<typeof revokeApiToken>>
>;

export type RevokeApiTokenMutationError = unknown;
export type RevokeApiTokenMutationVariables = { tokenId: string };

/**
 * @summary Revoke Api Token
 */
export const useRevokeApiToken = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof revokeApiToken>>,
    TError,
    RevokeApiTokenMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof revokeApiToken>>,
  TError,
  RevokeApiTokenMutationVariables,
  TContext
> => {
  return useMutation(getRevokeApiTokenMutationOptions(options));
};
export const getLoginUrl = () => {
  return `/api/auth/login`;
};

/**
 * @summary Login
 */
export const login = async (
  loginIn: LoginIn,
  options?: Parameters<typeof customFetch>[1],
): Promise<TokenOut> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
  return customFetch<TokenOut>(getLoginUrl(), {
    ...options,
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...getHeaders(options?.headers),
    },
    body: JSON.stringify(loginIn),
  });
};

export const getLoginMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof login>>,
    TError,
    LoginMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof login>>,
  TError,
  LoginMutationVariables,
  TContext
> => {
  const mutationKey = ["login"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof login>>,
    LoginMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return login(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof login>>
>;
export type LoginMutationBody = LoginIn;
export type LoginMutationError = unknown;
export type LoginMutationVariables = { data: LoginIn };

/**
 * @summary Login
 */
export const useLogin = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof login>>,
    TError,
    LoginMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof login>>,
  TError,
  LoginMutationVariables,
  TContext
> => {
  return useMutation(getLoginMutationOptions(options));
};
export const getGetCurrentUserUrl = () => {
  return `/api/auth/me`;
};

/**
 * @summary Get Current User
 */
export const getCurrentUser = async (
  options?: Parameters<typeof customFetch>[1],
): Promise<UserOut> => {
  return customFetch<UserOut>(getGetCurrentUserUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetCurrentUserQueryKey = () => {
  return [`/api/auth/me`] as const;
};

export const getGetCurrentUserQueryOptions = <
  TData = Awaited<ReturnType<typeof getCurrentUser>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getCurrentUser>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCurrentUserQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCurrentUser>>> = ({
    signal,
  }) => getCurrentUser({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCurrentUser>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetCurrentUserQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCurrentUser>>
>;
export type GetCurrentUserQueryError = unknown;

/**
 * @summary Get Current User
 */

export function useGetCurrentUser<
  TData = Awaited<ReturnType<typeof getCurrentUser>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getCurrentUser>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetCurrentUserQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getRefreshTokenUrl = () => {
  return `/api/auth/refresh`;
};

/**
 * Issue a fresh access token for the caller (call before the current one expires).
 * @summary Refresh Token
 */
export const refreshToken = async (
  options?: Parameters<typeof customFetch>[1],
): Promise<TokenOut> => {
  return customFetch<TokenOut>(getRefreshTokenUrl(), {
    ...options,
    method: "POST",
  });
};

export const getRefreshTokenMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof refreshToken>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof refreshToken>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["refreshToken"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof refreshToken>>,
    void
  > = () => {
    return refreshToken(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RefreshTokenMutationResult = NonNullable<
  Awaited<ReturnType<typeof refreshToken>>
>;

export type RefreshTokenMutationError = unknown;

/**
 * @summary Refresh Token
 */
export const useRefreshToken = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof refreshToken>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof refreshToken>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getRefreshTokenMutationOptions(options));
};
export const getRegisterUrl = () => {
  return `/api/auth/register`;
};

/**
 * Self-service sign-up; only available when `REGISTRATION_OPEN=true`.
 * @summary Register
 */
export const register = async (
  registerIn: RegisterIn,
  options?: Parameters<typeof customFetch>[1],
): Promise<TokenOut> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
  return customFetch<TokenOut>(getRegisterUrl(), {
    ...options,
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...getHeaders(options?.headers),
    },
    body: JSON.stringify(registerIn),
  });
};

export const getRegisterMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof register>>,
    TError,
    RegisterMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof register>>,
  TError,
  RegisterMutationVariables,
  TContext
> => {
  const mutationKey = ["register"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof register>>,
    RegisterMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return register(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RegisterMutationResult = NonNullable<
  Awaited<ReturnType<typeof register>>
>;
export type RegisterMutationBody = RegisterIn;
export type RegisterMutationError = unknown;
export type RegisterMutationVariables = { data: RegisterIn };

/**
 * @summary Register
 */
export const useRegister = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof register>>,
    TError,
    RegisterMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof register>>,
  TError,
  RegisterMutationVariables,
  TContext
> => {
  return useMutation(getRegisterMutationOptions(options));
};
