/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * Instant task: a + b.
 * @summary Run Add
 */
export const RunAddBody = zod.object({
  a: zod.int(),
  b: zod.int(),
});

export const RunAddResponse = zod
  .object({
    error: zod.union([zod.string(), zod.null()]).optional(),
    id: zod.string(),
    progress: zod
      .union([
        zod.object({
          current: zod.int(),
          total: zod.int(),
        }),
        zod.null(),
      ])
      .optional(),
    ready: zod.boolean(),
    result: zod
      .union([zod.unknown(), zod.null()])
      .optional()
      .describe("Return value once SUCCESS"),
    state: zod.enum([
      "PENDING",
      "RECEIVED",
      "STARTED",
      "PROGRESS",
      "RETRY",
      "SUCCESS",
      "FAILURE",
      "REVOKED",
      "REJECTED",
      "IGNORED",
    ]),
    stream_url: zod
      .string()
      .describe(
        "Signed SSE endpoint: one `status` event (this schema) per state change",
      ),
  })
  .describe(
    "Snapshot of a Celery task. Until `ready` is true, follow it via `stream_url`\n(Server-Sent Events) or poll `GET \/api\/tasks\/{id}`.",
  );

/**
 * Slow task that reports PROGRESS (n steps of `delay` seconds).
 * @summary Run Count
 */
export const runCountBodyDelayDefault = 0.5;
export const runCountBodyDelayMin = 0;
export const runCountBodyDelayMax = 10;

export const runCountBodyNDefault = 10;
export const runCountBodyNMax = 600;

export const RunCountBody = zod.object({
  delay: zod
    .number()
    .min(runCountBodyDelayMin)
    .max(runCountBodyDelayMax)
    .default(runCountBodyDelayDefault)
    .describe("Seconds per step"),
  n: zod.int().min(1).max(runCountBodyNMax).default(runCountBodyNDefault),
});

export const RunCountResponse = zod
  .object({
    error: zod.union([zod.string(), zod.null()]).optional(),
    id: zod.string(),
    progress: zod
      .union([
        zod.object({
          current: zod.int(),
          total: zod.int(),
        }),
        zod.null(),
      ])
      .optional(),
    ready: zod.boolean(),
    result: zod
      .union([zod.unknown(), zod.null()])
      .optional()
      .describe("Return value once SUCCESS"),
    state: zod.enum([
      "PENDING",
      "RECEIVED",
      "STARTED",
      "PROGRESS",
      "RETRY",
      "SUCCESS",
      "FAILURE",
      "REVOKED",
      "REJECTED",
      "IGNORED",
    ]),
    stream_url: zod
      .string()
      .describe(
        "Signed SSE endpoint: one `status` event (this schema) per state change",
      ),
  })
  .describe(
    "Snapshot of a Celery task. Until `ready` is true, follow it via `stream_url`\n(Server-Sent Events) or poll `GET \/api\/tasks\/{id}`.",
  );

/**
 * Task that reads the database (dataset and row counts).
 * @summary Run Dataset Summary
 */
export const RunDatasetSummaryResponse = zod
  .object({
    error: zod.union([zod.string(), zod.null()]).optional(),
    id: zod.string(),
    progress: zod
      .union([
        zod.object({
          current: zod.int(),
          total: zod.int(),
        }),
        zod.null(),
      ])
      .optional(),
    ready: zod.boolean(),
    result: zod
      .union([zod.unknown(), zod.null()])
      .optional()
      .describe("Return value once SUCCESS"),
    state: zod.enum([
      "PENDING",
      "RECEIVED",
      "STARTED",
      "PROGRESS",
      "RETRY",
      "SUCCESS",
      "FAILURE",
      "REVOKED",
      "REJECTED",
      "IGNORED",
    ]),
    stream_url: zod
      .string()
      .describe(
        "Signed SSE endpoint: one `status` event (this schema) per state change",
      ),
  })
  .describe(
    "Snapshot of a Celery task. Until `ready` is true, follow it via `stream_url`\n(Server-Sent Events) or poll `GET \/api\/tasks\/{id}`.",
  );

/**
 * Task that raises, to see FAILURE handling end to end.
 * @summary Run Fail
 */
export const RunFailResponse = zod
  .object({
    error: zod.union([zod.string(), zod.null()]).optional(),
    id: zod.string(),
    progress: zod
      .union([
        zod.object({
          current: zod.int(),
          total: zod.int(),
        }),
        zod.null(),
      ])
      .optional(),
    ready: zod.boolean(),
    result: zod
      .union([zod.unknown(), zod.null()])
      .optional()
      .describe("Return value once SUCCESS"),
    state: zod.enum([
      "PENDING",
      "RECEIVED",
      "STARTED",
      "PROGRESS",
      "RETRY",
      "SUCCESS",
      "FAILURE",
      "REVOKED",
      "REJECTED",
      "IGNORED",
    ]),
    stream_url: zod
      .string()
      .describe(
        "Signed SSE endpoint: one `status` event (this schema) per state change",
      ),
  })
  .describe(
    "Snapshot of a Celery task. Until `ready` is true, follow it via `stream_url`\n(Server-Sent Events) or poll `GET \/api\/tasks\/{id}`.",
  );

/**
 * @summary Get Task
 */
export const GetTaskParams = zod.object({
  task_id: zod.string(),
});

export const GetTaskResponse = zod
  .object({
    error: zod.union([zod.string(), zod.null()]).optional(),
    id: zod.string(),
    progress: zod
      .union([
        zod.object({
          current: zod.int(),
          total: zod.int(),
        }),
        zod.null(),
      ])
      .optional(),
    ready: zod.boolean(),
    result: zod
      .union([zod.unknown(), zod.null()])
      .optional()
      .describe("Return value once SUCCESS"),
    state: zod.enum([
      "PENDING",
      "RECEIVED",
      "STARTED",
      "PROGRESS",
      "RETRY",
      "SUCCESS",
      "FAILURE",
      "REVOKED",
      "REJECTED",
      "IGNORED",
    ]),
    stream_url: zod
      .string()
      .describe(
        "Signed SSE endpoint: one `status` event (this schema) per state change",
      ),
  })
  .describe(
    "Snapshot of a Celery task. Until `ready` is true, follow it via `stream_url`\n(Server-Sent Events) or poll `GET \/api\/tasks\/{id}`.",
  );

/**
 * Server-Sent Events with the task's status: one `status` event now and one per change,
 * then the connection closes once the task is ready (text/event-stream, not part of the JSON
 * contract — use `TaskOut.stream_url`, which carries the signature).
 *
 * The stream also closes after `tasks.WATCH_TIMEOUT`; EventSource reconnects on its own.
 * @summary Stream Task Events
 */
export const StreamTaskEventsParams = zod.object({
  task_id: zod.string(),
});

export const StreamTaskEventsQueryParams = zod.object({
  sig: zod.string(),
});

export const StreamTaskEventsResponse = zod.unknown();
