# Generated by Django 5.2.6 on 2025-11-06 15:48

import config.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.CharField(default=config.models.id_gen, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('ordering', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Paragraph',
                'verbose_name_plural': 'Paragraphs',
                'ordering': ['ordering', '-created'],
            },
        ),
        migrations.CreateModel(
            name='PhotoForParagraph',
            fields=[
                ('id', models.CharField(default=config.models.id_gen, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='report.paragraph')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.photo')),
            ],
            options={
                'verbose_name': 'Photo for Paragraph',
                'verbose_name_plural': 'Photos for Paragraphs',
                'ordering': ['ordering', '-created'],
            },
        ),
        migrations.CreateModel(
            name='PhotoForTravelDay',
            fields=[
                ('id', models.CharField(default=config.models.id_gen, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.photo')),
            ],
            options={
                'verbose_name': 'Photo for Travel Day',
                'verbose_name_plural': 'Photos for Travel Days',
                'ordering': ['ordering', '-created'],
            },
        ),
        migrations.CreateModel(
            name='TravelDay',
            fields=[
                ('id', models.CharField(default=config.models.id_gen, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('day_number', models.PositiveIntegerField(default=0)),
                ('date', models.DateField()),
                ('headline', models.TextField()),
            ],
            options={
                'verbose_name': 'Travel Day',
                'verbose_name_plural': 'Travel Days',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='TravelDayPart',
            fields=[
                ('id', models.CharField(default=config.models.id_gen, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('headline', models.TextField()),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='report.travelday')),
            ],
            options={
                'verbose_name': 'Travel Day Part',
                'verbose_name_plural': 'Travel Day Parts',
                'ordering': ['ordering', '-created'],
            },
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.AddField(
            model_name='photofortravelday',
            name='travel_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='report.travelday'),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='day_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='report.traveldaypart'),
        ),
    ]
