/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as DatasetsRouteImport } from "./routes/datasets";
import { Route as DocumentsRouteImport } from "./routes/documents";
import { Route as GalleryRouteImport } from "./routes/gallery";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as NotesRouteImport } from "./routes/notes";
import { Route as TasksRouteImport } from "./routes/tasks";
import { Route as HistoryResourceObjectIdRouteImport } from "./routes/history.$resource.$objectId";
import { Route as LineageResourceObjectIdRouteImport } from "./routes/lineage.$resource.$objectId";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const DatasetsRoute = DatasetsRouteImport.update({
  id: "/datasets",
  path: "/datasets",
  getParentRoute: () => rootRouteImport,
} as any);
const DocumentsRoute = DocumentsRouteImport.update({
  id: "/documents",
  path: "/documents",
  getParentRoute: () => rootRouteImport,
} as any);
const GalleryRoute = GalleryRouteImport.update({
  id: "/gallery",
  path: "/gallery",
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const NotesRoute = NotesRouteImport.update({
  id: "/notes",
  path: "/notes",
  getParentRoute: () => rootRouteImport,
} as any);
const TasksRoute = TasksRouteImport.update({
  id: "/tasks",
  path: "/tasks",
  getParentRoute: () => rootRouteImport,
} as any);
const HistoryResourceObjectIdRoute = HistoryResourceObjectIdRouteImport.update({
  id: "/history/$resource/$objectId",
  path: "/history/$resource/$objectId",
  getParentRoute: () => rootRouteImport,
} as any);
const LineageResourceObjectIdRoute = LineageResourceObjectIdRouteImport.update({
  id: "/lineage/$resource/$objectId",
  path: "/lineage/$resource/$objectId",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/datasets": typeof DatasetsRoute;
  "/documents": typeof DocumentsRoute;
  "/gallery": typeof GalleryRoute;
  "/login": typeof LoginRoute;
  "/notes": typeof NotesRoute;
  "/tasks": typeof TasksRoute;
  "/history/$resource/$objectId": typeof HistoryResourceObjectIdRoute;
  "/lineage/$resource/$objectId": typeof LineageResourceObjectIdRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/datasets": typeof DatasetsRoute;
  "/documents": typeof DocumentsRoute;
  "/gallery": typeof GalleryRoute;
  "/login": typeof LoginRoute;
  "/notes": typeof NotesRoute;
  "/tasks": typeof TasksRoute;
  "/history/$resource/$objectId": typeof HistoryResourceObjectIdRoute;
  "/lineage/$resource/$objectId": typeof LineageResourceObjectIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/datasets": typeof DatasetsRoute;
  "/documents": typeof DocumentsRoute;
  "/gallery": typeof GalleryRoute;
  "/login": typeof LoginRoute;
  "/notes": typeof NotesRoute;
  "/tasks": typeof TasksRoute;
  "/history/$resource/$objectId": typeof HistoryResourceObjectIdRoute;
  "/lineage/$resource/$objectId": typeof LineageResourceObjectIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/datasets"
    | "/documents"
    | "/gallery"
    | "/login"
    | "/notes"
    | "/tasks"
    | "/history/$resource/$objectId"
    | "/lineage/$resource/$objectId";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/datasets"
    | "/documents"
    | "/gallery"
    | "/login"
    | "/notes"
    | "/tasks"
    | "/history/$resource/$objectId"
    | "/lineage/$resource/$objectId";
  id:
    | "__root__"
    | "/"
    | "/datasets"
    | "/documents"
    | "/gallery"
    | "/login"
    | "/notes"
    | "/tasks"
    | "/history/$resource/$objectId"
    | "/lineage/$resource/$objectId";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DatasetsRoute: typeof DatasetsRoute;
  DocumentsRoute: typeof DocumentsRoute;
  GalleryRoute: typeof GalleryRoute;
  LoginRoute: typeof LoginRoute;
  NotesRoute: typeof NotesRoute;
  TasksRoute: typeof TasksRoute;
  HistoryResourceObjectIdRoute: typeof HistoryResourceObjectIdRoute;
  LineageResourceObjectIdRoute: typeof LineageResourceObjectIdRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/datasets": {
      id: "/datasets";
      path: "/datasets";
      fullPath: "/datasets";
      preLoaderRoute: typeof DatasetsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/documents": {
      id: "/documents";
      path: "/documents";
      fullPath: "/documents";
      preLoaderRoute: typeof DocumentsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/gallery": {
      id: "/gallery";
      path: "/gallery";
      fullPath: "/gallery";
      preLoaderRoute: typeof GalleryRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/notes": {
      id: "/notes";
      path: "/notes";
      fullPath: "/notes";
      preLoaderRoute: typeof NotesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/tasks": {
      id: "/tasks";
      path: "/tasks";
      fullPath: "/tasks";
      preLoaderRoute: typeof TasksRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/history/$resource/$objectId": {
      id: "/history/$resource/$objectId";
      path: "/history/$resource/$objectId";
      fullPath: "/history/$resource/$objectId";
      preLoaderRoute: typeof HistoryResourceObjectIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/lineage/$resource/$objectId": {
      id: "/lineage/$resource/$objectId";
      path: "/lineage/$resource/$objectId";
      fullPath: "/lineage/$resource/$objectId";
      preLoaderRoute: typeof LineageResourceObjectIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatasetsRoute: DatasetsRoute,
  DocumentsRoute: DocumentsRoute,
  GalleryRoute: GalleryRoute,
  LoginRoute: LoginRoute,
  NotesRoute: NotesRoute,
  TasksRoute: TasksRoute,
  HistoryResourceObjectIdRoute: HistoryResourceObjectIdRoute,
  LineageResourceObjectIdRoute: LineageResourceObjectIdRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
