/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as DatasetsRouteImport } from "./routes/datasets";
import { Route as DocumentsRouteImport } from "./routes/documents";
import { Route as GalleryRouteImport } from "./routes/gallery";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as TasksRouteImport } from "./routes/tasks";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const DatasetsRoute = DatasetsRouteImport.update({
  id: "/datasets",
  path: "/datasets",
  getParentRoute: () => rootRouteImport,
} as any);
const DocumentsRoute = DocumentsRouteImport.update({
  id: "/documents",
  path: "/documents",
  getParentRoute: () => rootRouteImport,
} as any);
const GalleryRoute = GalleryRouteImport.update({
  id: "/gallery",
  path: "/gallery",
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const TasksRoute = TasksRouteImport.update({
  id: "/tasks",
  path: "/tasks",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/datasets": typeof DatasetsRoute;
  "/documents": typeof DocumentsRoute;
  "/gallery": typeof GalleryRoute;
  "/login": typeof LoginRoute;
  "/tasks": typeof TasksRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/datasets": typeof DatasetsRoute;
  "/documents": typeof DocumentsRoute;
  "/gallery": typeof GalleryRoute;
  "/login": typeof LoginRoute;
  "/tasks": typeof TasksRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/datasets": typeof DatasetsRoute;
  "/documents": typeof DocumentsRoute;
  "/gallery": typeof GalleryRoute;
  "/login": typeof LoginRoute;
  "/tasks": typeof TasksRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    "/" | "/datasets" | "/documents" | "/gallery" | "/login" | "/tasks";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/datasets" | "/documents" | "/gallery" | "/login" | "/tasks";
  id:
    | "__root__"
    | "/"
    | "/datasets"
    | "/documents"
    | "/gallery"
    | "/login"
    | "/tasks";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DatasetsRoute: typeof DatasetsRoute;
  DocumentsRoute: typeof DocumentsRoute;
  GalleryRoute: typeof GalleryRoute;
  LoginRoute: typeof LoginRoute;
  TasksRoute: typeof TasksRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/datasets": {
      id: "/datasets";
      path: "/datasets";
      fullPath: "/datasets";
      preLoaderRoute: typeof DatasetsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/documents": {
      id: "/documents";
      path: "/documents";
      fullPath: "/documents";
      preLoaderRoute: typeof DocumentsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/gallery": {
      id: "/gallery";
      path: "/gallery";
      fullPath: "/gallery";
      preLoaderRoute: typeof GalleryRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/tasks": {
      id: "/tasks";
      path: "/tasks";
      fullPath: "/tasks";
      preLoaderRoute: typeof TasksRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatasetsRoute: DatasetsRoute,
  DocumentsRoute: DocumentsRoute,
  GalleryRoute: GalleryRoute,
  LoginRoute: LoginRoute,
  TasksRoute: TasksRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
