/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * @summary List Documents
 */
export const listDocumentsQueryPageDefault = 1;

export const ListDocumentsQueryParams = zod.object({
  page: zod.int().min(1).default(listDocumentsQueryPageDefault),
  page_size: zod.union([zod.int().min(1), zod.null()]).optional(),
});

export const listDocumentsResponseItemsItemNameMax = 255;

export const ListDocumentsResponse = zod.object({
  count: zod.int(),
  items: zod.array(
    zod.object({
      content_type: zod.string(),
      created: zod.iso.datetime({ offset: true }),
      download_url: zod.string(),
      id: zod.uuid(),
      name: zod.string().max(listDocumentsResponseItemsItemNameMax),
      size: zod.int(),
    }),
  ),
});

/**
 * Upload one or more files as multipart/form-data (field name `files`).
 * @summary Upload Documents
 */
export const UploadDocumentsBody = zod.object({
  files: zod.array(zod.instanceof(File)),
});

export const uploadDocumentsResponseNameMax = 255;

export const UploadDocumentsResponseItem = zod.object({
  content_type: zod.string(),
  created: zod.iso.datetime({ offset: true }),
  download_url: zod.string(),
  id: zod.uuid(),
  name: zod.string().max(uploadDocumentsResponseNameMax),
  size: zod.int(),
});
export const UploadDocumentsResponse = zod.array(UploadDocumentsResponseItem);

/**
 * @summary Delete Document
 */
export const DeleteDocumentParams = zod.object({
  document_id: zod.uuid(),
});

export const DeleteDocumentResponse = zod.void();

/**
 * @summary Get Document
 */
export const GetDocumentParams = zod.object({
  document_id: zod.uuid(),
});

export const getDocumentResponseNameMax = 255;

export const GetDocumentResponse = zod.object({
  content_type: zod.string(),
  created: zod.iso.datetime({ offset: true }),
  download_url: zod.string(),
  id: zod.uuid(),
  name: zod.string().max(getDocumentResponseNameMax),
  size: zod.int(),
});

/**
 * Streams the stored file as an attachment (binary response, not part of the JSON contract).
 *
 * Public but signed: use the `download_url` from `DocumentOut`, links expire after an hour.
 * The signature names the owner; their tenant context is opened just for the lookup.
 * @summary Download Document
 */
export const DownloadDocumentParams = zod.object({
  document_id: zod.uuid(),
});

export const DownloadDocumentQueryParams = zod.object({
  sig: zod.string(),
});

export const DownloadDocumentResponse = zod.unknown();
