/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */

import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";
import { customFetch } from "../../lib/custom-fetch";
import type {
  ListMediaItemsParams,
  MediaItemOut,
  PagedMediaItemOut,
  UploadMediaItemsBody,
} from "../model";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getListMediaItemsUrl = (params?: ListMediaItemsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/gallery?${stringifiedParams}`
    : `/api/gallery`;
};

/**
 * @summary List Media Items
 */
export const listMediaItems = async (
  params?: ListMediaItemsParams,
  options?: Parameters<typeof customFetch>[1],
): Promise<PagedMediaItemOut> => {
  return customFetch<PagedMediaItemOut>(getListMediaItemsUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getListMediaItemsQueryKey = (params?: ListMediaItemsParams) => {
  return [`/api/gallery`, ...(params ? [params] : [])] as const;
};

export const getListMediaItemsQueryOptions = <
  TData = Awaited<ReturnType<typeof listMediaItems>>,
  TError = unknown,
>(
  params?: ListMediaItemsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listMediaItems>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListMediaItemsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listMediaItems>>> = ({
    signal,
  }) => listMediaItems(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listMediaItems>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListMediaItemsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listMediaItems>>
>;
export type ListMediaItemsQueryError = unknown;

/**
 * @summary List Media Items
 */

export function useListMediaItems<
  TData = Awaited<ReturnType<typeof listMediaItems>>,
  TError = unknown,
>(
  params?: ListMediaItemsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listMediaItems>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListMediaItemsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getUploadMediaItemsUrl = () => {
  return `/api/gallery/upload`;
};

/**
 * Upload images and/or videos as multipart/form-data (field name `files`).
 * @summary Upload Media Items
 */
export const uploadMediaItems = async (
  uploadMediaItemsBody: UploadMediaItemsBody,
  options?: Parameters<typeof customFetch>[1],
): Promise<MediaItemOut[]> => {
  const formData = new FormData();
  uploadMediaItemsBody.files.forEach((value) =>
    formData.append(`files`, value),
  );

  return customFetch<MediaItemOut[]>(getUploadMediaItemsUrl(), {
    ...options,
    method: "POST",
    body: formData,
  });
};

export const getUploadMediaItemsMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof uploadMediaItems>>,
    TError,
    UploadMediaItemsMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof uploadMediaItems>>,
  TError,
  UploadMediaItemsMutationVariables,
  TContext
> => {
  const mutationKey = ["uploadMediaItems"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof uploadMediaItems>>,
    UploadMediaItemsMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return uploadMediaItems(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UploadMediaItemsMutationResult = NonNullable<
  Awaited<ReturnType<typeof uploadMediaItems>>
>;
export type UploadMediaItemsMutationBody = UploadMediaItemsBody;
export type UploadMediaItemsMutationError = unknown;
export type UploadMediaItemsMutationVariables = { data: UploadMediaItemsBody };

/**
 * @summary Upload Media Items
 */
export const useUploadMediaItems = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof uploadMediaItems>>,
    TError,
    UploadMediaItemsMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof uploadMediaItems>>,
  TError,
  UploadMediaItemsMutationVariables,
  TContext
> => {
  return useMutation(getUploadMediaItemsMutationOptions(options));
};
export const getDeleteMediaItemUrl = (mediaItemId: string) => {
  return `/api/gallery/${mediaItemId}`;
};

/**
 * Soft delete; the stored object stays (see `delete_document` in apps/documents/api.py).
 * @summary Delete Media Item
 */
export const deleteMediaItem = async (
  mediaItemId: string,
  options?: Parameters<typeof customFetch>[1],
): Promise<void> => {
  return customFetch<void>(getDeleteMediaItemUrl(mediaItemId), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteMediaItemMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteMediaItem>>,
    TError,
    DeleteMediaItemMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteMediaItem>>,
  TError,
  DeleteMediaItemMutationVariables,
  TContext
> => {
  const mutationKey = ["deleteMediaItem"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteMediaItem>>,
    DeleteMediaItemMutationVariables
  > = (props) => {
    const { mediaItemId } = props ?? {};

    return deleteMediaItem(mediaItemId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteMediaItemMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteMediaItem>>
>;

export type DeleteMediaItemMutationError = unknown;
export type DeleteMediaItemMutationVariables = { mediaItemId: string };

/**
 * @summary Delete Media Item
 */
export const useDeleteMediaItem = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteMediaItem>>,
    TError,
    DeleteMediaItemMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteMediaItem>>,
  TError,
  DeleteMediaItemMutationVariables,
  TContext
> => {
  return useMutation(getDeleteMediaItemMutationOptions(options));
};
export const getGetMediaItemUrl = (mediaItemId: string) => {
  return `/api/gallery/${mediaItemId}`;
};

/**
 * @summary Get Media Item
 */
export const getMediaItem = async (
  mediaItemId: string,
  options?: Parameters<typeof customFetch>[1],
): Promise<MediaItemOut> => {
  return customFetch<MediaItemOut>(getGetMediaItemUrl(mediaItemId), {
    ...options,
    method: "GET",
  });
};

export const getGetMediaItemQueryKey = (mediaItemId: string) => {
  return [`/api/gallery/${mediaItemId}`] as const;
};

export const getGetMediaItemQueryOptions = <
  TData = Awaited<ReturnType<typeof getMediaItem>>,
  TError = unknown,
>(
  mediaItemId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getMediaItem>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetMediaItemQueryKey(mediaItemId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMediaItem>>> = ({
    signal,
  }) => getMediaItem(mediaItemId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: mediaItemId !== null && mediaItemId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getMediaItem>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetMediaItemQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMediaItem>>
>;
export type GetMediaItemQueryError = unknown;

/**
 * @summary Get Media Item
 */

export function useGetMediaItem<
  TData = Awaited<ReturnType<typeof getMediaItem>>,
  TError = unknown,
>(
  mediaItemId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getMediaItem>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetMediaItemQueryOptions(mediaItemId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return withQueryKey(query, queryOptions.queryKey);
}
