/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * Liveness: the process answers requests. No dependencies are touched (a database outage
 * must not get the app restarted). Public.
 * @summary Health Check
 */
export const HealthCheckResponse = zod.object({
  status: zod.literal("ok").meta({ title: "Status" }),
});

/**
 * Readiness: database reachable and migrated, Celery broker up, storage buckets present.
 * 503 with the failing checks otherwise — gate load balancers / compose on this. Public.
 * @summary Ready
 */
export const ReadyResponse = zod.object({
  checks: zod.array(
    zod.object({
      detail: zod.string(),
      name: zod.string(),
      ok: zod.boolean(),
    }),
  ),
  status: zod.enum(["ok", "fail"]),
});
