/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */

import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { useQuery } from "@tanstack/react-query";
import { customFetch } from "../../lib/custom-fetch";
import type { GetLineageParams, GraphOut, HistoryOut } from "../model";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetHistoryUrl = (resource: string, objectId: string) => {
  return `/api/history/${resource}/${objectId}`;
};

/**
 * Every version of one object, newest first, grouped into the saves that produced them.
 *
 * `resource` is the model name in lower case (`dataset`, `document`, `mediaitem`); the tracked
 * models are the ones with history (`apps/core/history.py`). Another tenant's object is a 404,
 * like everywhere else — the event tables carry the same row-level security policy.
 * @summary Get History
 */
export const getHistory = async (
  resource: string,
  objectId: string,
  options?: Parameters<typeof customFetch>[1],
): Promise<HistoryOut> => {
  return customFetch<HistoryOut>(getGetHistoryUrl(resource, objectId), {
    ...options,
    method: "GET",
  });
};

export const getGetHistoryQueryKey = (resource: string, objectId: string) => {
  return [`/api/history/${resource}/${objectId}`] as const;
};

export const getGetHistoryQueryOptions = <
  TData = Awaited<ReturnType<typeof getHistory>>,
  TError = unknown,
>(
  resource: string,
  objectId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getHistory>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetHistoryQueryKey(resource, objectId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getHistory>>> = ({
    signal,
  }) => getHistory(resource, objectId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled:
      resource !== null &&
      resource !== undefined &&
      objectId !== null &&
      objectId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getHistory>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetHistoryQueryResult = NonNullable<
  Awaited<ReturnType<typeof getHistory>>
>;
export type GetHistoryQueryError = unknown;

/**
 * @summary Get History
 */

export function useGetHistory<
  TData = Awaited<ReturnType<typeof getHistory>>,
  TError = unknown,
>(
  resource: string,
  objectId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getHistory>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetHistoryQueryOptions(resource, objectId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getGetLineageUrl = (
  resource: string,
  objectId: string,
  params?: GetLineageParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/lineage/${resource}/${objectId}?${stringifiedParams}`
    : `/api/lineage/${resource}/${objectId}`;
};

/**
 * What this object was built from and what was built from it, transitively.
 *
 * `resource` is the model name in lower case, as for the revision history. Edges point at a
 * *version* of a source, so an edge marked `is_stale` says the source has moved on since —
 * the derived object was built from something that no longer reads that way.
 * @summary Get Lineage
 */
export const getLineage = async (
  resource: string,
  objectId: string,
  params?: GetLineageParams,
  options?: Parameters<typeof customFetch>[1],
): Promise<GraphOut> => {
  return customFetch<GraphOut>(getGetLineageUrl(resource, objectId, params), {
    ...options,
    method: "GET",
  });
};

export const getGetLineageQueryKey = (
  resource: string,
  objectId: string,
  params?: GetLineageParams,
) => {
  return [
    `/api/lineage/${resource}/${objectId}`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetLineageQueryOptions = <
  TData = Awaited<ReturnType<typeof getLineage>>,
  TError = unknown,
>(
  resource: string,
  objectId: string,
  params?: GetLineageParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getLineage>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetLineageQueryKey(resource, objectId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getLineage>>> = ({
    signal,
  }) => getLineage(resource, objectId, params, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled:
      resource !== null &&
      resource !== undefined &&
      objectId !== null &&
      objectId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getLineage>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetLineageQueryResult = NonNullable<
  Awaited<ReturnType<typeof getLineage>>
>;
export type GetLineageQueryError = unknown;

/**
 * @summary Get Lineage
 */

export function useGetLineage<
  TData = Awaited<ReturnType<typeof getLineage>>,
  TError = unknown,
>(
  resource: string,
  objectId: string,
  params?: GetLineageParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getLineage>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetLineageQueryOptions(
    resource,
    objectId,
    params,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return withQueryKey(query, queryOptions.queryKey);
}
