/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */

import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";
import { customFetch } from "../../lib/custom-fetch";
import type {
  ListNotesParams,
  MergeNotesIn,
  NoteIn,
  NoteOut,
  NotePatch,
  PagedNoteOut,
} from "../model";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getListNotesUrl = (params?: ListNotesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/notes?${stringifiedParams}`
    : `/api/notes`;
};

/**
 * @summary List Notes
 */
export const listNotes = async (
  params?: ListNotesParams,
  options?: Parameters<typeof customFetch>[1],
): Promise<PagedNoteOut> => {
  return customFetch<PagedNoteOut>(getListNotesUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getListNotesQueryKey = (params?: ListNotesParams) => {
  return [`/api/notes`, ...(params ? [params] : [])] as const;
};

export const getListNotesQueryOptions = <
  TData = Awaited<ReturnType<typeof listNotes>>,
  TError = unknown,
>(
  params?: ListNotesParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listNotes>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListNotesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listNotes>>> = ({
    signal,
  }) => listNotes(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listNotes>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListNotesQueryResult = NonNullable<
  Awaited<ReturnType<typeof listNotes>>
>;
export type ListNotesQueryError = unknown;

/**
 * @summary List Notes
 */

export function useListNotes<
  TData = Awaited<ReturnType<typeof listNotes>>,
  TError = unknown,
>(
  params?: ListNotesParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listNotes>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListNotesQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getCreateNoteUrl = () => {
  return `/api/notes`;
};

/**
 * @summary Create Note
 */
export const createNote = async (
  noteIn: NoteIn,
  options?: Parameters<typeof customFetch>[1],
): Promise<NoteOut> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
  return customFetch<NoteOut>(getCreateNoteUrl(), {
    ...options,
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...getHeaders(options?.headers),
    },
    body: JSON.stringify(noteIn),
  });
};

export const getCreateNoteMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createNote>>,
    TError,
    CreateNoteMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createNote>>,
  TError,
  CreateNoteMutationVariables,
  TContext
> => {
  const mutationKey = ["createNote"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createNote>>,
    CreateNoteMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return createNote(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateNoteMutationResult = NonNullable<
  Awaited<ReturnType<typeof createNote>>
>;
export type CreateNoteMutationBody = NoteIn;
export type CreateNoteMutationError = unknown;
export type CreateNoteMutationVariables = { data: NoteIn };

/**
 * @summary Create Note
 */
export const useCreateNote = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createNote>>,
    TError,
    CreateNoteMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createNote>>,
  TError,
  CreateNoteMutationVariables,
  TContext
> => {
  return useMutation(getCreateNoteMutationOptions(options));
};
export const getMergeNotesUrl = () => {
  return `/api/notes/merge`;
};

/**
 * Join several notes into a new one, with an edge to the current version of each source.
 *
 * Registered before `/notes/{note_id}` so "merge" is not read as an id.
 * @summary Merge Notes
 */
export const mergeNotes = async (
  mergeNotesIn: MergeNotesIn,
  options?: Parameters<typeof customFetch>[1],
): Promise<NoteOut> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
  return customFetch<NoteOut>(getMergeNotesUrl(), {
    ...options,
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...getHeaders(options?.headers),
    },
    body: JSON.stringify(mergeNotesIn),
  });
};

export const getMergeNotesMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof mergeNotes>>,
    TError,
    MergeNotesMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof mergeNotes>>,
  TError,
  MergeNotesMutationVariables,
  TContext
> => {
  const mutationKey = ["mergeNotes"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof mergeNotes>>,
    MergeNotesMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return mergeNotes(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type MergeNotesMutationResult = NonNullable<
  Awaited<ReturnType<typeof mergeNotes>>
>;
export type MergeNotesMutationBody = MergeNotesIn;
export type MergeNotesMutationError = unknown;
export type MergeNotesMutationVariables = { data: MergeNotesIn };

/**
 * @summary Merge Notes
 */
export const useMergeNotes = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof mergeNotes>>,
    TError,
    MergeNotesMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof mergeNotes>>,
  TError,
  MergeNotesMutationVariables,
  TContext
> => {
  return useMutation(getMergeNotesMutationOptions(options));
};
export const getDeleteNoteUrl = (noteId: string) => {
  return `/api/notes/${noteId}`;
};

/**
 * Soft delete (apps/core/models.py): the row keeps its place in the version chain, and
 * `objects` stops returning it — so a second delete is a 404 exactly as before.
 *
 * Notes merged from it keep their edges, and those still resolve: the source row is still
 * there, one version further on. That is the reason deletes are soft.
 * @summary Delete Note
 */
export const deleteNote = async (
  noteId: string,
  options?: Parameters<typeof customFetch>[1],
): Promise<void> => {
  return customFetch<void>(getDeleteNoteUrl(noteId), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteNoteMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteNote>>,
    TError,
    DeleteNoteMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteNote>>,
  TError,
  DeleteNoteMutationVariables,
  TContext
> => {
  const mutationKey = ["deleteNote"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteNote>>,
    DeleteNoteMutationVariables
  > = (props) => {
    const { noteId } = props ?? {};

    return deleteNote(noteId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteNoteMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteNote>>
>;

export type DeleteNoteMutationError = unknown;
export type DeleteNoteMutationVariables = { noteId: string };

/**
 * @summary Delete Note
 */
export const useDeleteNote = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteNote>>,
    TError,
    DeleteNoteMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteNote>>,
  TError,
  DeleteNoteMutationVariables,
  TContext
> => {
  return useMutation(getDeleteNoteMutationOptions(options));
};
export const getGetNoteUrl = (noteId: string) => {
  return `/api/notes/${noteId}`;
};

/**
 * @summary Get Note
 */
export const getNote = async (
  noteId: string,
  options?: Parameters<typeof customFetch>[1],
): Promise<NoteOut> => {
  return customFetch<NoteOut>(getGetNoteUrl(noteId), {
    ...options,
    method: "GET",
  });
};

export const getGetNoteQueryKey = (noteId: string) => {
  return [`/api/notes/${noteId}`] as const;
};

export const getGetNoteQueryOptions = <
  TData = Awaited<ReturnType<typeof getNote>>,
  TError = unknown,
>(
  noteId: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getNote>>, TError, TData>;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetNoteQueryKey(noteId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getNote>>> = ({
    signal,
  }) => getNote(noteId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: noteId !== null && noteId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getNote>>, TError, TData> & {
    queryKey: QueryKey;
  };
};

export type GetNoteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getNote>>
>;
export type GetNoteQueryError = unknown;

/**
 * @summary Get Note
 */

export function useGetNote<
  TData = Awaited<ReturnType<typeof getNote>>,
  TError = unknown,
>(
  noteId: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getNote>>, TError, TData>;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetNoteQueryOptions(noteId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getPatchNoteUrl = (noteId: string) => {
  return `/api/notes/${noteId}`;
};

/**
 * PATCH: change only the fields the client sent.
 * @summary Patch Note
 */
export const patchNote = async (
  noteId: string,
  notePatch: NotePatch,
  options?: Parameters<typeof customFetch>[1],
): Promise<NoteOut> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
  return customFetch<NoteOut>(getPatchNoteUrl(noteId), {
    ...options,
    method: "PATCH",
    headers: {
      "Content-Type": "application/json",
      ...getHeaders(options?.headers),
    },
    body: JSON.stringify(notePatch),
  });
};

export const getPatchNoteMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patchNote>>,
    TError,
    PatchNoteMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof patchNote>>,
  TError,
  PatchNoteMutationVariables,
  TContext
> => {
  const mutationKey = ["patchNote"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof patchNote>>,
    PatchNoteMutationVariables
  > = (props) => {
    const { noteId, data } = props ?? {};

    return patchNote(noteId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PatchNoteMutationResult = NonNullable<
  Awaited<ReturnType<typeof patchNote>>
>;
export type PatchNoteMutationBody = NotePatch;
export type PatchNoteMutationError = unknown;
export type PatchNoteMutationVariables = { noteId: string; data: NotePatch };

/**
 * @summary Patch Note
 */
export const usePatchNote = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patchNote>>,
    TError,
    PatchNoteMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof patchNote>>,
  TError,
  PatchNoteMutationVariables,
  TContext
> => {
  return useMutation(getPatchNoteMutationOptions(options));
};
export const getUpdateNoteUrl = (noteId: string) => {
  return `/api/notes/${noteId}`;
};

/**
 * PUT: replace every field with the payload (schema defaults for omitted ones).
 * @summary Update Note
 */
export const updateNote = async (
  noteId: string,
  noteIn: NoteIn,
  options?: Parameters<typeof customFetch>[1],
): Promise<NoteOut> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
  return customFetch<NoteOut>(getUpdateNoteUrl(noteId), {
    ...options,
    method: "PUT",
    headers: {
      "Content-Type": "application/json",
      ...getHeaders(options?.headers),
    },
    body: JSON.stringify(noteIn),
  });
};

export const getUpdateNoteMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateNote>>,
    TError,
    UpdateNoteMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateNote>>,
  TError,
  UpdateNoteMutationVariables,
  TContext
> => {
  const mutationKey = ["updateNote"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateNote>>,
    UpdateNoteMutationVariables
  > = (props) => {
    const { noteId, data } = props ?? {};

    return updateNote(noteId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateNoteMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateNote>>
>;
export type UpdateNoteMutationBody = NoteIn;
export type UpdateNoteMutationError = unknown;
export type UpdateNoteMutationVariables = { noteId: string; data: NoteIn };

/**
 * @summary Update Note
 */
export const useUpdateNote = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateNote>>,
    TError,
    UpdateNoteMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateNote>>,
  TError,
  UpdateNoteMutationVariables,
  TContext
> => {
  return useMutation(getUpdateNoteMutationOptions(options));
};
