/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */

import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { useQuery } from "@tanstack/react-query";
import { customFetch } from "../../lib/custom-fetch";
import type { HealthOut, ReadyOut } from "../model";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getHealthCheckUrl = () => {
  return `/api/health`;
};

/**
 * Liveness: the process answers requests. No dependencies are touched (a database outage
 * must not get the app restarted). Public.
 * @summary Health Check
 */
export const healthCheck = async (
  options?: Parameters<typeof customFetch>[1],
): Promise<HealthOut> => {
  return customFetch<HealthOut>(getHealthCheckUrl(), {
    ...options,
    method: "GET",
  });
};

export const getHealthCheckQueryKey = () => {
  return [`/api/health`] as const;
};

export const getHealthCheckQueryOptions = <
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthCheckQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({
    signal,
  }) => healthCheck({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type HealthCheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthCheck>>
>;
export type HealthCheckQueryError = unknown;

/**
 * @summary Health Check
 */

export function useHealthCheck<
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getHealthCheckQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getReadyUrl = () => {
  return `/api/ready`;
};

/**
 * Readiness: database reachable and migrated, Celery broker up, storage buckets present.
 * 503 with the failing checks otherwise — gate load balancers / compose on this. Public.
 * @summary Ready
 */
export const ready = async (
  options?: Parameters<typeof customFetch>[1],
): Promise<ReadyOut> => {
  return customFetch<ReadyOut>(getReadyUrl(), {
    ...options,
    method: "GET",
  });
};

export const getReadyQueryKey = () => {
  return [`/api/ready`] as const;
};

export const getReadyQueryOptions = <
  TData = Awaited<ReturnType<typeof ready>>,
  TError = ReadyOut,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof ready>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getReadyQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof ready>>> = ({
    signal,
  }) => ready({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof ready>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ReadyQueryResult = NonNullable<Awaited<ReturnType<typeof ready>>>;
export type ReadyQueryError = ReadyOut;

/**
 * @summary Ready
 */

export function useReady<
  TData = Awaited<ReturnType<typeof ready>>,
  TError = ReadyOut,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof ready>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getReadyQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return withQueryKey(query, queryOptions.queryKey);
}
