# Generated by Django 6.1 on 2026-08-31 15:49

import django.db.models.deletion
import django.db.models.functions.datetime
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lineage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=models.Func(function="uuidv7"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("target_pgh_id", models.UUIDField()),
                ("source_pgh_id", models.UUIDField()),
                ("source_obj_id", models.UUIDField()),
                ("source_version", models.PositiveIntegerField()),
                ("pgh_context", models.UUIDField(default=None, null=True)),
                (
                    "created",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "target_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created", "-id"],
                "indexes": [
                    models.Index(
                        fields=["owner", "source_obj_id", "source_version"],
                        name="core_lineag_owner_i_5e99b4_idx",
                    ),
                    models.Index(
                        fields=["owner", "target_pgh_id"],
                        name="core_lineag_owner_i_c28867_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("target_pgh_id", "source_pgh_id"),
                        name="uniq_lineage_edge",
                    )
                ],
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="lineage",
            trigger=pgtrigger.compiler.Trigger(
                name="no_hard_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot delete rows from % table', TG_TABLE_NAME;",
                    hash="933a92d9115cb33bdaccc9975ce8d8fc4ee6fb03",
                    operation="DELETE",
                    pgid="pgtrigger_no_hard_delete_5323e",
                    table="core_lineage",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="lineage",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="17136221843c1229178cd5816ad2eed1f5e13d82",
                    operation="UPDATE",
                    pgid="pgtrigger_append_only_17d28",
                    table="core_lineage",
                    when="BEFORE",
                ),
            ),
        ),
    ]
