# Generated by Django 6.1 on 2026-09-01 14:00

import django.db.models.functions.datetime
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommandRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=models.Func(function="uuidv7"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("version", models.PositiveIntegerField(db_default=1, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(db_index=True, default=None, editable=False, null=True),
                ),
                ("name", models.CharField(max_length=100)),
                ("arguments", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-created", "-id"],
                "abstract": False,
                "indexes": [
                    models.Index(fields=["name", "-created"], name="core_comman_name_93c965_idx")
                ],
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="commandrun",
            trigger=pgtrigger.compiler.Trigger(
                name="no_hard_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot delete rows from % table', TG_TABLE_NAME;",
                    hash="03e74f07a9fdc2cd10fe6af4e316c5cef1fc1496",
                    operation="DELETE",
                    pgid="pgtrigger_no_hard_delete_a647a",
                    table="core_commandrun",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="commandrun",
            trigger=pgtrigger.compiler.Trigger(
                name="bump_version",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="NEW.version = OLD.version + 1; NEW.modified = STATEMENT_TIMESTAMP(); RETURN NEW;",
                    hash="2333a4a99f6e42ce289ee83622cd3ebb2a3ca26d",
                    operation="UPDATE",
                    pgid="pgtrigger_bump_version_c2e4e",
                    table="core_commandrun",
                    when="BEFORE",
                ),
            ),
        ),
    ]
