# Generated by Django 6.1 on 2026-09-01 18:07

import django.core.serializers.json
import django_pydantic_field.compat.django
import django_pydantic_field.fields
from django.db import migrations

import apps.core.lineage


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_commandrun_commandrun_no_hard_delete_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lineage",
            name="stack",
            field=django_pydantic_field.fields.PydanticSchemaField(
                config=None,
                default=list,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                schema=django_pydantic_field.compat.django.GenericContainer(
                    list, (apps.core.lineage.StackFrame,)
                ),
            ),
        ),
    ]
