# Generated by Django 6.1 on 2026-09-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_lineage_stack"),
    ]

    operations = [
        migrations.AddField(
            model_name="lineage",
            name="release",
            field=models.CharField(default="", editable=False, max_length=64),
        ),
    ]
