# Generated by Django 6.1 on 2026-09-02 07:59

import django.db.models.functions.datetime
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_lineage_release"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceSnippet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=models.Func(function="uuidv7"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sha", models.CharField(editable=False, max_length=64, unique=True)),
                ("text", models.TextField(editable=False)),
                (
                    "created",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="sourcesnippet",
            trigger=pgtrigger.compiler.Trigger(
                name="no_hard_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot delete rows from % table', TG_TABLE_NAME;",
                    hash="1e03cfc6c9b8ec486d36dbe676fe36624db433eb",
                    operation="DELETE",
                    pgid="pgtrigger_no_hard_delete_88ae1",
                    table="core_sourcesnippet",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="sourcesnippet",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="d58f9e65b4c0f3f7f57b85c4246be173cca0366c",
                    operation="UPDATE",
                    pgid="pgtrigger_append_only_0db9d",
                    table="core_sourcesnippet",
                    when="BEFORE",
                ),
            ),
        ),
    ]
