# Generated by Django 6.1 on 2026-09-02 08:18

import django.db.models.deletion
import django.db.models.functions.datetime
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_sourcesnippet_sourcesnippet_no_hard_delete_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lineage",
            name="request",
            field=models.UUIDField(db_index=True, default=None, editable=False, null=True),
        ),
        migrations.CreateModel(
            name="RequestRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=models.Func(function="uuidv7"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "request_id",
                    models.CharField(blank=True, db_index=True, editable=False, max_length=64),
                ),
                ("method", models.CharField(editable=False, max_length=16)),
                ("path", models.TextField(editable=False)),
                ("query", models.JSONField(default=dict, editable=False)),
                ("headers", models.JSONField(default=dict, editable=False)),
                (
                    "content_type",
                    models.CharField(blank=True, editable=False, max_length=200),
                ),
                ("body", models.JSONField(default=None, editable=False, null=True)),
                ("body_size", models.PositiveIntegerField(default=0, editable=False)),
                ("body_status", models.CharField(editable=False, max_length=16)),
                (
                    "created",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "indexes": [
                    models.Index(
                        fields=["owner", "-created"],
                        name="core_reques_owner_i_00280a_idx",
                    )
                ],
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="requestrecord",
            trigger=pgtrigger.compiler.Trigger(
                name="no_hard_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot delete rows from % table', TG_TABLE_NAME;",
                    hash="a0dcd7929c7d2a100d7092092dfac425fc76ddb4",
                    operation="DELETE",
                    pgid="pgtrigger_no_hard_delete_970e2",
                    table="core_requestrecord",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="requestrecord",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="f4af5e23c163833543c943aa79095f60a9bfd7c7",
                    operation="UPDATE",
                    pgid="pgtrigger_append_only_edc74",
                    table="core_requestrecord",
                    when="BEFORE",
                ),
            ),
        ),
    ]
