# Generated by Django 6.1 on 2026-09-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_lineage_request_requestrecord_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="requestrecord",
            name="body",
        ),
        migrations.RemoveField(
            model_name="requestrecord",
            name="headers",
        ),
        migrations.RemoveField(
            model_name="requestrecord",
            name="query",
        ),
        migrations.AddField(
            model_name="requestrecord",
            name="sent_body",
            field=models.JSONField(default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="requestrecord",
            name="sent_headers",
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="requestrecord",
            name="sent_query",
            field=models.JSONField(default=dict, editable=False),
        ),
    ]
