# Generated by Django 6.1 on 2026-08-31 19:09

import django.db.models.deletion
import django.db.models.functions.datetime
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pghistory", "0007_auto_20250421_0444"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=models.Func(function="uuidv7"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("version", models.PositiveIntegerField(db_default=1, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(db_index=True, default=None, editable=False, null=True),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField(blank=True)),
                (
                    "owner",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created", "-id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NoteEvent",
            fields=[
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=models.Func(function="uuidv7"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pgh_schema", models.TextField(db_default="2026-08")),
                ("pgh_archive", models.JSONField(default=None, null=True)),
                (
                    "id",
                    models.UUIDField(
                        db_default=models.Func(function="uuidv7"),
                        editable=False,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("version", models.PositiveIntegerField(db_default=1, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(default=None, editable=False, null=True),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField(blank=True)),
                (
                    "owner",
                    models.ForeignKey(
                        db_constraint=False,
                        editable=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pgh_context",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pghistory.context",
                    ),
                ),
                (
                    "pgh_obj",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="events",
                        to="notes.note",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="note",
            index=models.Index(
                fields=["owner", "-created", "-id"],
                name="notes_note_owner_i_5159ea_idx",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="note",
            trigger=pgtrigger.compiler.Trigger(
                name="no_hard_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot delete rows from % table', TG_TABLE_NAME;",
                    hash="e1fc78adce5ce938fab4998f7d271e283dc95a88",
                    operation="DELETE",
                    pgid="pgtrigger_no_hard_delete_95e9e",
                    table="notes_note",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="note",
            trigger=pgtrigger.compiler.Trigger(
                name="bump_version",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="NEW.version = OLD.version + 1; NEW.modified = STATEMENT_TIMESTAMP(); RETURN NEW;",
                    hash="a5ef44d3dc477c4a67fcbc303362d0a2132c8e49",
                    operation="UPDATE",
                    pgid="pgtrigger_bump_version_36c59",
                    table="notes_note",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="note",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "notes_noteevent" ("body", "created", "deleted_at", "id", "modified", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "title", "version") VALUES (NEW."body", NEW."created", NEW."deleted_at", NEW."id", NEW."modified", NEW."owner_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."title", NEW."version"); RETURN NULL;',
                    hash="0fcd78e8c156eb0e4d1135a5854162adaf1a5c17",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_7ed5b",
                    table="notes_note",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="note",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "notes_noteevent" ("body", "created", "deleted_at", "id", "modified", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "title", "version") VALUES (NEW."body", NEW."created", NEW."deleted_at", NEW."id", NEW."modified", NEW."owner_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."title", NEW."version"); RETURN NULL;',
                    hash="470c23dbfb131a0799d6c93c09a5e98cff0df4f7",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_38f06",
                    table="notes_note",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="noteevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="48f92673ff961830d4e988decc0ac78bd96d7891",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_3ddc3",
                    table="notes_noteevent",
                    when="BEFORE",
                ),
            ),
        ),
    ]
