# Generated by Django 6.1 on 2026-08-31 19:23

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="note",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="note",
            name="update_update",
        ),
        migrations.AddField(
            model_name="note",
            name="tags",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="noteevent",
            name="tags",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="noteevent",
            name="pgh_schema",
            field=models.TextField(db_default="2026-09"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="note",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "notes_noteevent" ("body", "created", "deleted_at", "id", "modified", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tags", "title", "version") VALUES (NEW."body", NEW."created", NEW."deleted_at", NEW."id", NEW."modified", NEW."owner_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."tags", NEW."title", NEW."version"); RETURN NULL;',
                    hash="f16cc29fc71e288c6b711c9a1a3ef9f4e9f24bd5",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_7ed5b",
                    table="notes_note",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="note",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "notes_noteevent" ("body", "created", "deleted_at", "id", "modified", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tags", "title", "version") VALUES (NEW."body", NEW."created", NEW."deleted_at", NEW."id", NEW."modified", NEW."owner_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."tags", NEW."title", NEW."version"); RETURN NULL;',
                    hash="ce177c890c28d7526393d2fe0c05ba56f49a6e93",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_38f06",
                    table="notes_note",
                    when="AFTER",
                ),
            ),
        ),
    ]
