# Generated by Django 6.1 on 2026-09-02 06:56

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0002_remove_note_insert_insert_remove_note_update_update_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="noteevent",
            name="pgh_release",
            field=models.TextField(
                db_default=django.db.models.functions.comparison.Cast(
                    django.db.models.functions.comparison.NullIf(
                        models.Func(
                            models.Value("dx.release"),
                            models.Value(True),
                            function="current_setting",
                        ),
                        models.Value(""),
                    ),
                    models.TextField(),
                ),
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="noteevent",
            name="pgh_stack",
            field=models.JSONField(
                db_default=django.db.models.functions.comparison.Cast(
                    django.db.models.functions.comparison.NullIf(
                        models.Func(
                            models.Value("dx.stack"),
                            models.Value(True),
                            function="current_setting",
                        ),
                        models.Value(""),
                    ),
                    models.JSONField(),
                ),
                null=True,
            ),
        ),
    ]
