# Generated by Django 5.2.6 on 2025-11-06 15:48

import config.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.CharField(default=config.models.id_gen, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.CharField(default=config.models.id_gen, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('nicknames', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PersonInGroup',
            fields=[
                ('id', models.CharField(default=config.models.id_gen, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.group')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.person')),
            ],
            options={
                'verbose_name': 'Person in Group',
                'verbose_name_plural': 'Persons in Groups',
                'ordering': ['-group__created', '-person__created'],
            },
        ),
        migrations.CreateModel(
            name='PersonOnATrip',
            fields=[
                ('id', models.CharField(default=config.models.id_gen, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('fitness_level', models.TextField(blank=True, null=True)),
                ('expectations', models.TextField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='persons.person')),
            ],
            options={
                'verbose_name': 'Person on a Trip',
                'verbose_name_plural': 'Persons on Trips',
                'ordering': ['-created'],
            },
        ),
        migrations.DeleteModel(
            name='Persons',
        ),
    ]
