# Generated by Django 5.2.6 on 2025-11-06 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_group_person_personingroup_persononatrip_and_more'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persononatrip',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='trips.trip'),
        ),
        migrations.AlterUniqueTogether(
            name='personingroup',
            unique_together={('person', 'group')},
        ),
    ]
