# Generated by Django 6.1 on 2026-09-02 13:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="pageregion",
            name="region_x_in_unit",
        ),
        migrations.RemoveConstraint(
            model_name="pageregion",
            name="region_y_in_unit",
        ),
        migrations.AlterField(
            model_name="pageregion",
            name="x0",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pageregion",
            name="x1",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pageregion",
            name="y0",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pageregion",
            name="y1",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pageregionevent",
            name="x0",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pageregionevent",
            name="x1",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pageregionevent",
            name="y0",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pageregionevent",
            name="y1",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="pageregion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("x0__isnull", True), ("x1__isnull", True)),
                    models.Q(("x0__gte", 0), ("x0__lte", models.F("x1")), ("x1__lte", 1)),
                    _connector="OR",
                ),
                name="region_x_in_unit",
            ),
        ),
        migrations.AddConstraint(
            model_name="pageregion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("y0__isnull", True), ("y1__isnull", True)),
                    models.Q(("y0__gte", 0), ("y0__lte", models.F("y1")), ("y1__lte", 1)),
                    _connector="OR",
                ),
                name="region_y_in_unit",
            ),
        ),
    ]
