# Generated by Django 6.1 on 2026-09-02 18:26

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_remove_pageregion_region_x_in_unit_and_more"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="documentcontent",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="documentcontent",
            name="update_update",
        ),
        migrations.AddField(
            model_name="documentcontent",
            name="title",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="documentcontentevent",
            name="title",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="blobevent",
            name="pgh_schema",
            field=models.TextField(db_default="2026-09-02b"),
        ),
        migrations.AlterField(
            model_name="documentcontentevent",
            name="pgh_schema",
            field=models.TextField(db_default="2026-09-02b"),
        ),
        migrations.AlterField(
            model_name="documentevent",
            name="pgh_schema",
            field=models.TextField(db_default="2026-09-02b"),
        ),
        migrations.AlterField(
            model_name="extractorevent",
            name="pgh_schema",
            field=models.TextField(db_default="2026-09-02b"),
        ),
        migrations.AlterField(
            model_name="nodeevent",
            name="pgh_schema",
            field=models.TextField(db_default="2026-09-02b"),
        ),
        migrations.AlterField(
            model_name="pageevent",
            name="pgh_schema",
            field=models.TextField(db_default="2026-09-02b"),
        ),
        migrations.AlterField(
            model_name="pageregionevent",
            name="pgh_schema",
            field=models.TextField(db_default="2026-09-02b"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="documentcontent",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "documents_documentcontentevent" ("blob_id", "conf_stats", "created", "date_conf", "date_edtf", "date_max", "date_min", "date_source", "deleted_at", "document_id", "error", "extractor_id", "finished_at", "html", "id", "is_current", "modified", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "raw_output_id", "started_at", "stats", "status", "text", "title", "version") VALUES (NEW."blob_id", NEW."conf_stats", NEW."created", NEW."date_conf", NEW."date_edtf", NEW."date_max", NEW."date_min", NEW."date_source", NEW."deleted_at", NEW."document_id", NEW."error", NEW."extractor_id", NEW."finished_at", NEW."html", NEW."id", NEW."is_current", NEW."modified", NEW."owner_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."raw_output_id", NEW."started_at", NEW."stats", NEW."status", NEW."text", NEW."title", NEW."version"); RETURN NULL;',
                    hash="640f421a3c7ce0d0afebb415b30382ec374ebb9e",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_5fe6e",
                    table="documents_documentcontent",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="documentcontent",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "documents_documentcontentevent" ("blob_id", "conf_stats", "created", "date_conf", "date_edtf", "date_max", "date_min", "date_source", "deleted_at", "document_id", "error", "extractor_id", "finished_at", "html", "id", "is_current", "modified", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "raw_output_id", "started_at", "stats", "status", "text", "title", "version") VALUES (NEW."blob_id", NEW."conf_stats", NEW."created", NEW."date_conf", NEW."date_edtf", NEW."date_max", NEW."date_min", NEW."date_source", NEW."deleted_at", NEW."document_id", NEW."error", NEW."extractor_id", NEW."finished_at", NEW."html", NEW."id", NEW."is_current", NEW."modified", NEW."owner_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."raw_output_id", NEW."started_at", NEW."stats", NEW."status", NEW."text", NEW."title", NEW."version"); RETURN NULL;',
                    hash="fa5d34d4b7afe17c41b678ecadca8ea8903eb872",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_3a7fb",
                    table="documents_documentcontent",
                    when="AFTER",
                ),
            ),
        ),
    ]
