# Generated by Django 6.1 on 2026-08-31 15:44

import django.db.models.deletion
import django.db.models.functions.datetime
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models

import apps.core.models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0002_alter_document_file_alter_document_owner_and_more"),
        ("pghistory", "0007_auto_20250421_0444"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentEvent",
            fields=[
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=models.Func(function="uuidv7"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pgh_schema", models.TextField(db_default="2026-08")),
                ("pgh_archive", models.JSONField(default=None, null=True)),
                (
                    "id",
                    models.UUIDField(
                        db_default=models.Func(function="uuidv7"),
                        editable=False,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("version", models.PositiveIntegerField(db_default=1, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(default=None, editable=False, null=True),
                ),
                (
                    "file",
                    models.FileField(upload_to=apps.core.models.owned_upload_path),
                ),
                ("name", models.CharField(max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=100)),
                ("size", models.PositiveBigIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="document",
            name="deleted_at",
            field=models.DateTimeField(db_index=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="version",
            field=models.PositiveIntegerField(db_default=1, editable=False),
        ),
        migrations.AlterField(
            model_name="document",
            name="created",
            field=models.DateTimeField(
                db_default=django.db.models.functions.datetime.Now(), editable=False
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="id",
            field=models.UUIDField(
                db_default=models.Func(function="uuidv7"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="modified",
            field=models.DateTimeField(
                db_default=django.db.models.functions.datetime.Now(), editable=False
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="document",
            trigger=pgtrigger.compiler.Trigger(
                name="no_hard_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot delete rows from % table', TG_TABLE_NAME;",
                    hash="8e2f76eb00151afabfb41f19d8ea74b88d0c74bd",
                    operation="DELETE",
                    pgid="pgtrigger_no_hard_delete_f2567",
                    table="documents_document",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="document",
            trigger=pgtrigger.compiler.Trigger(
                name="bump_version",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="NEW.version = OLD.version + 1; NEW.modified = STATEMENT_TIMESTAMP(); RETURN NEW;",
                    hash="21313a7f382503547040991f32b81d6c766c2dfb",
                    operation="UPDATE",
                    pgid="pgtrigger_bump_version_0644c",
                    table="documents_document",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="document",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "documents_documentevent" ("content_type", "created", "deleted_at", "file", "id", "modified", "name", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "size", "version") VALUES (NEW."content_type", NEW."created", NEW."deleted_at", NEW."file", NEW."id", NEW."modified", NEW."name", NEW."owner_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."size", NEW."version"); RETURN NULL;',
                    hash="1422ec032c1643cf3a30c557cb6e98c549af8010",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_be524",
                    table="documents_document",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="document",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "documents_documentevent" ("content_type", "created", "deleted_at", "file", "id", "modified", "name", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "size", "version") VALUES (NEW."content_type", NEW."created", NEW."deleted_at", NEW."file", NEW."id", NEW."modified", NEW."name", NEW."owner_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."size", NEW."version"); RETURN NULL;',
                    hash="64bd83980bdd6ada35d4ac46c2336154400f7ed2",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_a3ed6",
                    table="documents_document",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddField(
            model_name="documentevent",
            name="owner",
            field=models.ForeignKey(
                db_constraint=False,
                editable=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="documentevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="documentevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="documents.document",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="documentevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="401291d04b3fa5f3d2b51241f67950bd6896846e",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_9e7ed",
                    table="documents_documentevent",
                    when="BEFORE",
                ),
            ),
        ),
    ]
