# Generated by Django 6.1 on 2026-09-03 05:02

import django.core.serializers.json
import django.db.models.deletion
import django.db.models.functions.datetime
import django_pydantic_field.fields
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models

import apps.documents.models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0003_remove_documentcontent_insert_insert_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="blobevent",
            name="pgh_schema",
            field=models.TextField(db_default="2026-09-03"),
        ),
        migrations.AlterField(
            model_name="documentcontentevent",
            name="pgh_schema",
            field=models.TextField(db_default="2026-09-03"),
        ),
        migrations.AlterField(
            model_name="documentevent",
            name="pgh_schema",
            field=models.TextField(db_default="2026-09-03"),
        ),
        migrations.AlterField(
            model_name="extractorevent",
            name="pgh_schema",
            field=models.TextField(db_default="2026-09-03"),
        ),
        migrations.AlterField(
            model_name="nodeevent",
            name="pgh_schema",
            field=models.TextField(db_default="2026-09-03"),
        ),
        migrations.AlterField(
            model_name="pageevent",
            name="pgh_schema",
            field=models.TextField(db_default="2026-09-03"),
        ),
        migrations.AlterField(
            model_name="pageregionevent",
            name="pgh_schema",
            field=models.TextField(db_default="2026-09-03"),
        ),
        migrations.CreateModel(
            name="DocumentContentDraft",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=models.Func(function="uuidv7"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("version", models.PositiveIntegerField(db_default=1, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(db_index=True, default=None, editable=False, null=True),
                ),
                (
                    "state",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None,
                        default=apps.documents.models.ExtractionState,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        schema=apps.documents.models.ExtractionState,
                    ),
                ),
                (
                    "blob",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="documents.blob",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drafts",
                        to="documents.document",
                    ),
                ),
                (
                    "extractor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="documents.extractor",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created", "-id"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["owner", "-created", "-id"],
                        name="documents_d_owner_i_fcc59e_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("document", "blob", "extractor"),
                        name="uniq_active_content_draft",
                    )
                ],
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="documentcontentdraft",
            trigger=pgtrigger.compiler.Trigger(
                name="no_hard_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot delete rows from % table', TG_TABLE_NAME;",
                    hash="8de6b7d6e4b24ad1810e2d5a279ab8d19041ff7e",
                    operation="DELETE",
                    pgid="pgtrigger_no_hard_delete_15c45",
                    table="documents_documentcontentdraft",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="documentcontentdraft",
            trigger=pgtrigger.compiler.Trigger(
                name="bump_version",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="NEW.version = OLD.version + 1; NEW.modified = STATEMENT_TIMESTAMP(); RETURN NEW;",
                    hash="9a67ce45a953e9507fbda00a88814f47905e0e67",
                    operation="UPDATE",
                    pgid="pgtrigger_bump_version_26336",
                    table="documents_documentcontentdraft",
                    when="BEFORE",
                ),
            ),
        ),
    ]
