# Generated by Django 6.1 on 2026-08-31 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "documents",
            "0003_documentevent_document_deleted_at_document_version_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentevent",
            name="pgh_schema",
            field=models.TextField(db_default="2026-09"),
        ),
    ]
