# Generated by Django 6.1 on 2026-09-03 06:39

import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0004_alter_blobevent_pgh_schema_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="document",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="document",
            name="update_update",
        ),
        migrations.AddField(
            model_name="document",
            name="md5",
            field=models.CharField(default="", max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="documentevent",
            name="md5",
            field=models.CharField(default="", max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="blobevent",
            name="pgh_schema",
            field=models.TextField(db_default="2026-09-03b"),
        ),
        migrations.AlterField(
            model_name="documentcontentevent",
            name="pgh_schema",
            field=models.TextField(db_default="2026-09-03b"),
        ),
        migrations.AlterField(
            model_name="documentevent",
            name="pgh_schema",
            field=models.TextField(db_default="2026-09-03b"),
        ),
        migrations.AlterField(
            model_name="extractorevent",
            name="pgh_schema",
            field=models.TextField(db_default="2026-09-03b"),
        ),
        migrations.AlterField(
            model_name="nodeevent",
            name="pgh_schema",
            field=models.TextField(db_default="2026-09-03b"),
        ),
        migrations.AlterField(
            model_name="pageevent",
            name="pgh_schema",
            field=models.TextField(db_default="2026-09-03b"),
        ),
        migrations.AlterField(
            model_name="pageregionevent",
            name="pgh_schema",
            field=models.TextField(db_default="2026-09-03b"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="document",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "documents_documentevent" ("created", "current_content_id", "deleted_at", "id", "md5", "meta", "modified", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "source_blob_id", "thumbnail_id", "title", "version") VALUES (NEW."created", NEW."current_content_id", NEW."deleted_at", NEW."id", NEW."md5", NEW."meta", NEW."modified", NEW."owner_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."source_blob_id", NEW."thumbnail_id", NEW."title", NEW."version"); RETURN NULL;',
                    hash="2489fe39eb5f43d0002bee7f0ad6820461b88084",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_be524",
                    table="documents_document",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="document",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "documents_documentevent" ("created", "current_content_id", "deleted_at", "id", "md5", "meta", "modified", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "source_blob_id", "thumbnail_id", "title", "version") VALUES (NEW."created", NEW."current_content_id", NEW."deleted_at", NEW."id", NEW."md5", NEW."meta", NEW."modified", NEW."owner_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."source_blob_id", NEW."thumbnail_id", NEW."title", NEW."version"); RETURN NULL;',
                    hash="9f0e4c72f2376c0540db0d504bb00fc3024de3d3",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_a3ed6",
                    table="documents_document",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("owner", "md5"),
                name="uniq_active_document_md5_per_owner",
            ),
        ),
    ]
