# Generated by Django 6.1 on 2026-09-02 08:18

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0005_documentevent_pgh_release_documentevent_pgh_stack"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentevent",
            name="pgh_request",
            field=models.UUIDField(
                db_default=django.db.models.functions.comparison.Cast(
                    django.db.models.functions.comparison.NullIf(
                        models.Func(
                            models.Value("dx.request"),
                            models.Value(True),
                            function="current_setting",
                        ),
                        models.Value(""),
                    ),
                    models.UUIDField(),
                ),
                db_index=True,
                null=True,
            ),
        ),
    ]
