/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */

import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";
import { customFetch } from "../../lib/custom-fetch";
import type {
  DocumentOut,
  DownloadDocumentParams,
  ListDocumentsParams,
  PagedDocumentOut,
  UploadDocumentsBody,
} from "../model";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getListDocumentsUrl = (params?: ListDocumentsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/documents?${stringifiedParams}`
    : `/api/documents`;
};

/**
 * @summary List Documents
 */
export const listDocuments = async (
  params?: ListDocumentsParams,
  options?: Parameters<typeof customFetch>[1],
): Promise<PagedDocumentOut> => {
  return customFetch<PagedDocumentOut>(getListDocumentsUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getListDocumentsQueryKey = (params?: ListDocumentsParams) => {
  return [`/api/documents`, ...(params ? [params] : [])] as const;
};

export const getListDocumentsQueryOptions = <
  TData = Awaited<ReturnType<typeof listDocuments>>,
  TError = unknown,
>(
  params?: ListDocumentsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listDocuments>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListDocumentsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listDocuments>>> = ({
    signal,
  }) => listDocuments(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listDocuments>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListDocumentsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listDocuments>>
>;
export type ListDocumentsQueryError = unknown;

/**
 * @summary List Documents
 */

export function useListDocuments<
  TData = Awaited<ReturnType<typeof listDocuments>>,
  TError = unknown,
>(
  params?: ListDocumentsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listDocuments>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListDocumentsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getUploadDocumentsUrl = () => {
  return `/api/documents/upload`;
};

/**
 * Upload one or more files as multipart/form-data (field name `files`).
 * @summary Upload Documents
 */
export const uploadDocuments = async (
  uploadDocumentsBody: UploadDocumentsBody,
  options?: Parameters<typeof customFetch>[1],
): Promise<DocumentOut[]> => {
  const formData = new FormData();
  uploadDocumentsBody.files.forEach((value) => formData.append(`files`, value));

  return customFetch<DocumentOut[]>(getUploadDocumentsUrl(), {
    ...options,
    method: "POST",
    body: formData,
  });
};

export const getUploadDocumentsMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof uploadDocuments>>,
    TError,
    UploadDocumentsMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof uploadDocuments>>,
  TError,
  UploadDocumentsMutationVariables,
  TContext
> => {
  const mutationKey = ["uploadDocuments"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof uploadDocuments>>,
    UploadDocumentsMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return uploadDocuments(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UploadDocumentsMutationResult = NonNullable<
  Awaited<ReturnType<typeof uploadDocuments>>
>;
export type UploadDocumentsMutationBody = UploadDocumentsBody;
export type UploadDocumentsMutationError = unknown;
export type UploadDocumentsMutationVariables = { data: UploadDocumentsBody };

/**
 * @summary Upload Documents
 */
export const useUploadDocuments = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof uploadDocuments>>,
    TError,
    UploadDocumentsMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof uploadDocuments>>,
  TError,
  UploadDocumentsMutationVariables,
  TContext
> => {
  return useMutation(getUploadDocumentsMutationOptions(options));
};
export const getDeleteDocumentUrl = (documentId: string) => {
  return `/api/documents/${documentId}`;
};

/**
 * @summary Delete Document
 */
export const deleteDocument = async (
  documentId: string,
  options?: Parameters<typeof customFetch>[1],
): Promise<void> => {
  return customFetch<void>(getDeleteDocumentUrl(documentId), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteDocumentMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteDocument>>,
    TError,
    DeleteDocumentMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteDocument>>,
  TError,
  DeleteDocumentMutationVariables,
  TContext
> => {
  const mutationKey = ["deleteDocument"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteDocument>>,
    DeleteDocumentMutationVariables
  > = (props) => {
    const { documentId } = props ?? {};

    return deleteDocument(documentId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteDocumentMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteDocument>>
>;

export type DeleteDocumentMutationError = unknown;
export type DeleteDocumentMutationVariables = { documentId: string };

/**
 * @summary Delete Document
 */
export const useDeleteDocument = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteDocument>>,
    TError,
    DeleteDocumentMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteDocument>>,
  TError,
  DeleteDocumentMutationVariables,
  TContext
> => {
  return useMutation(getDeleteDocumentMutationOptions(options));
};
export const getGetDocumentUrl = (documentId: string) => {
  return `/api/documents/${documentId}`;
};

/**
 * @summary Get Document
 */
export const getDocument = async (
  documentId: string,
  options?: Parameters<typeof customFetch>[1],
): Promise<DocumentOut> => {
  return customFetch<DocumentOut>(getGetDocumentUrl(documentId), {
    ...options,
    method: "GET",
  });
};

export const getGetDocumentQueryKey = (documentId: string) => {
  return [`/api/documents/${documentId}`] as const;
};

export const getGetDocumentQueryOptions = <
  TData = Awaited<ReturnType<typeof getDocument>>,
  TError = unknown,
>(
  documentId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getDocument>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetDocumentQueryKey(documentId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getDocument>>> = ({
    signal,
  }) => getDocument(documentId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: documentId !== null && documentId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getDocument>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetDocumentQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDocument>>
>;
export type GetDocumentQueryError = unknown;

/**
 * @summary Get Document
 */

export function useGetDocument<
  TData = Awaited<ReturnType<typeof getDocument>>,
  TError = unknown,
>(
  documentId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getDocument>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetDocumentQueryOptions(documentId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getDownloadDocumentUrl = (
  documentId: string,
  params: DownloadDocumentParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/documents/${documentId}/download?${stringifiedParams}`
    : `/api/documents/${documentId}/download`;
};

/**
 * Streams the stored file as an attachment (binary response, not part of the JSON contract).
 *
 * Public but signed: use the `download_url` from `DocumentOut`, links expire after an hour.
 * @summary Download Document
 */
export const downloadDocument = async (
  documentId: string,
  params: DownloadDocumentParams,
  options?: Parameters<typeof customFetch>[1],
): Promise<void> => {
  return customFetch<void>(getDownloadDocumentUrl(documentId, params), {
    ...options,
    method: "GET",
  });
};

export const getDownloadDocumentQueryKey = (
  documentId: string,
  params?: DownloadDocumentParams,
) => {
  return [
    `/api/documents/${documentId}/download`,
    ...(params ? [params] : []),
  ] as const;
};

export const getDownloadDocumentQueryOptions = <
  TData = Awaited<ReturnType<typeof downloadDocument>>,
  TError = unknown,
>(
  documentId: string,
  params: DownloadDocumentParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof downloadDocument>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getDownloadDocumentQueryKey(documentId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof downloadDocument>>
  > = ({ signal }) =>
    downloadDocument(documentId, params, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: documentId !== null && documentId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof downloadDocument>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type DownloadDocumentQueryResult = NonNullable<
  Awaited<ReturnType<typeof downloadDocument>>
>;
export type DownloadDocumentQueryError = unknown;

/**
 * @summary Download Document
 */

export function useDownloadDocument<
  TData = Awaited<ReturnType<typeof downloadDocument>>,
  TError = unknown,
>(
  documentId: string,
  params: DownloadDocumentParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof downloadDocument>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getDownloadDocumentQueryOptions(
    documentId,
    params,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return withQueryKey(query, queryOptions.queryKey);
}
