"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import logging
import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

PROJECT_NAME = "starter"

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

DEBUG = os.environ.get("DEBUG", False)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

SECRET_KEY = "django-insecure-43$)&qyk$cb($r)z1p5l(&n^98ua94h5uo59%9n5s&#p25#%j!" if DEBUG else os.environ[
    "SECRET_KEY"]

# Run celery tasks in the same process -> No celery broker required
# set eager via env to 0 or 1, else DEGUG is used
CELERY_EAGER = os.getenv("CELERY_EAGER")
CELERY_EAGER = str(CELERY_EAGER) == "1" if CELERY_EAGER is not None else DEBUG


if DEBUG:
    ALLOWED_HOSTS = ["*"]
else:
    ALLOWED_HOSTS = ["localhost:8000"]

if DEBUG:
    CSRF_TRUSTED_ORIGINS = [
        "http://localhost:8000",
        "http://localhost:3000",
        "https://api.starter.skytala-ci.com",
        "https://starter.skytala-ci.com",
    ]
else:
    CSRF_TRUSTED_ORIGINS = [
        "http://localhost:8000",
        "http://localhost:3000",
        "https://api.starter.skytala-ci.com",
        "https://starter.skytala-ci.com",
    ]

# share cookies across subdomains, so that the frontend can access the
# cookie and set it as X-CSRFToken header
if not DEBUG:
    # In production, use the real domain
    CSRF_COOKIE_DOMAIN = ".skytala-ci.com"
    SESSION_COOKIE_DOMAIN = ".skytala-ci.com"
else:
    # In development, let Django handle the cookie domain automatically
    CSRF_COOKIE_DOMAIN = None
    SESSION_COOKIE_DOMAIN = None

# Application definition

MODULES = [
    "core",
    "report",
    "iternary",
    "persons",
    "photos",
    "locations",
    "trips",
    # needle: add-module-to-settings
]

HEALTH_CHECK_MODULES = [
    "health_check",  # required
    "health_check.db",  # stock django health checkers
    "health_check.cache",
    "health_check.storage",
    "health_check.contrib.migrations",
    *(
        [
            "health_check.contrib.celery",
            "health_check.contrib.celery_ping",  # requires celery
        ]
        if not CELERY_EAGER 
        else []
    ),
    "health_check.contrib.psutil",
    "health_check.contrib.redis",
    # add s3 if you use minio
]


INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "django_db_logger",
    "django_celery_beat",
    "celery_progress",
    "dbbackup",
    *HEALTH_CHECK_MODULES,
    *MODULES,
]


HEALTH_CHECK = {  # TODO: Implement me, these are just copy&paste examples
    "DISK_USAGE_MAX": 90,  # percent
    "MEMORY_MIN": 100,  # in MB
    "SUBSETS": {
        "readyz": ["MigrationsHealthCheck", "DatabaseBackend"],
        "healthz": ["DatabaseBackend"],
    },
    # .....
}


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # Add custom middleware for JSON debug errors near the top
    "config.middleware.JsonDebugErrorHandlerMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    # 'hijack.middleware.HijackUserMiddleware', AttributeError: 'WSGIRequest' object has no attribute 'user
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # "django_structlog.middlewares.RequestMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

PG_PASSWORD = None
if os.environ.get("POSTGRES_PASSWORD_FILE"):
    with open(os.environ["POSTGRES_PASSWORD_FILE"]) as f:
        PG_PASSWORD = f.read().strip()

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_DB", PROJECT_NAME),
        "USER": os.environ.get("POSTGRES_USER", PROJECT_NAME),
        "PASSWORD": PG_PASSWORD or os.environ.get("POSTGRES_PASSWORD", PROJECT_NAME),
        "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
        "PORT": 5432,
    }
}

# Check if S3 credentials are configured
S3_ACCESS_KEY = os.environ.get("S3_ACCESS_KEY", "")
S3_SECRET_KEY = os.environ.get("S3_SECRET_KEY", "")
S3_ENDPOINT_URL = os.environ.get("S3_ENDPOINT_URL", "")
S3_BUCKET_NAME = os.environ.get("S3_BUCKET_NAME", f"{PROJECT_NAME}-backup")

# Use S3 if credentials are provided, otherwise use local filesystem
if S3_ACCESS_KEY and S3_SECRET_KEY and S3_ENDPOINT_URL:
    DBBACKUP_STORAGE = {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": {
            "endpoint_url": S3_ENDPOINT_URL,
            "access_key": S3_ACCESS_KEY,
            "secret_key": S3_SECRET_KEY,
            "bucket_name": S3_BUCKET_NAME,
            "default_acl": "private",
        },
    }
else:
    # Use local filesystem for backups
    BACKUP_DIR = BASE_DIR / "backups"
    BACKUP_DIR.mkdir(exist_ok=True)
    DBBACKUP_STORAGE = {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
        "OPTIONS": {
            "location": str(BACKUP_DIR),
        },
    }

# Media files settings
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
        "OPTIONS": {
            "location": MEDIA_ROOT,
        },
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
    "dbbackup": DBBACKUP_STORAGE,
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-en"
TIME_ZONE = "Europe/Berlin"
USE_I18N = False
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = os.environ.get("STATIC_URL", "static/")
STATIC_ROOT = os.environ.get("STATIC_ROOT", BASE_DIR)

STATICFILES_DIRS = [
    # BASE_DIR / "theme/static_src/node_modules",
    BASE_DIR / "static"  # Create a directory in the root of the project
]


# Default primary key field type: But see the base model in core.models where uuids are used
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "core.User"

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "https://starter.skytala-ci.com",
]
CORS_ALLOW_CREDENTIALS = True


CELERY_BROKER_URL = os.environ.get("CELERY_BROKER", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_BROKER", CELERY_BROKER_URL)
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"
REDIS_URL = os.environ.get("REDIS_URL", CELERY_BROKER_URL)

if CELERY_EAGER:  # TEST or DEBUG
    # all tasks will be executed locally by blocking until the task returns.
    # apply_async() and Task.delay() will return an EagerResult instance, which
    # emulates the API and behavior of AsyncResult, except the result is already evaluated.
    CELERY_TASK_ALWAYS_EAGER = True

    # Eagerly executed tasks (applied by task.apply(), or when the CELERY_TASK_ALWAYS_EAGER
    # setting is enabled), will propagate exceptions.
    CELERY_TASK_EAGER_PROPAGATES = True

CELERY_IMPORTS = ["core.tasks"]
