/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * @summary List Media Items
 */
export const listMediaItemsQueryPageDefault = 1;

export const ListMediaItemsQueryParams = zod.object({
  page: zod.int().min(1).default(listMediaItemsQueryPageDefault),
  page_size: zod.union([zod.int().min(1), zod.null()]).optional(),
});

export const listMediaItemsResponseItemsItemContentTypeMax = 100;

export const listMediaItemsResponseItemsItemKindMax = 5;

export const listMediaItemsResponseItemsItemNameMax = 255;

export const ListMediaItemsResponse = zod.object({
  count: zod.int(),
  items: zod.array(
    zod.object({
      content_type: zod
        .string()
        .max(listMediaItemsResponseItemsItemContentTypeMax),
      created: zod.iso.datetime({ offset: true }),
      id: zod.uuid(),
      kind: zod.string().max(listMediaItemsResponseItemsItemKindMax),
      name: zod.string().max(listMediaItemsResponseItemsItemNameMax),
      size: zod.int(),
      url: zod.string(),
    }),
  ),
});

/**
 * Upload images and/or videos as multipart/form-data (field name `files`).
 * @summary Upload Media Items
 */
export const UploadMediaItemsBody = zod.object({
  files: zod.array(zod.instanceof(File)),
});

export const uploadMediaItemsResponseContentTypeMax = 100;

export const uploadMediaItemsResponseKindMax = 5;

export const uploadMediaItemsResponseNameMax = 255;

export const UploadMediaItemsResponseItem = zod.object({
  content_type: zod.string().max(uploadMediaItemsResponseContentTypeMax),
  created: zod.iso.datetime({ offset: true }),
  id: zod.uuid(),
  kind: zod.string().max(uploadMediaItemsResponseKindMax),
  name: zod.string().max(uploadMediaItemsResponseNameMax),
  size: zod.int(),
  url: zod.string(),
});
export const UploadMediaItemsResponse = zod.array(UploadMediaItemsResponseItem);

/**
 * @summary Delete Media Item
 */
export const DeleteMediaItemParams = zod.object({
  media_item_id: zod.uuid(),
});

export const DeleteMediaItemResponse = zod.void();

/**
 * @summary Get Media Item
 */
export const GetMediaItemParams = zod.object({
  media_item_id: zod.uuid(),
});

export const getMediaItemResponseContentTypeMax = 100;

export const getMediaItemResponseKindMax = 5;

export const getMediaItemResponseNameMax = 255;

export const GetMediaItemResponse = zod.object({
  content_type: zod.string().max(getMediaItemResponseContentTypeMax),
  created: zod.iso.datetime({ offset: true }),
  id: zod.uuid(),
  kind: zod.string().max(getMediaItemResponseKindMax),
  name: zod.string().max(getMediaItemResponseNameMax),
  size: zod.int(),
  url: zod.string(),
});
