/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * @summary List Notes
 */
export const listNotesQueryPageDefault = 1;

export const ListNotesQueryParams = zod.object({
  page: zod.int().min(1).default(listNotesQueryPageDefault),
  page_size: zod.union([zod.int().min(1), zod.null()]).optional(),
});

export const listNotesResponseItemsItemTitleMax = 200;

export const ListNotesResponse = zod.object({
  count: zod.int(),
  items: zod.array(
    zod.object({
      body: zod.string(),
      created: zod.iso.datetime({ offset: true }),
      id: zod.uuid(),
      modified: zod.iso.datetime({ offset: true }),
      tags: zod.string().describe("Comma-separated, normalised on write"),
      title: zod.string().max(listNotesResponseItemsItemTitleMax),
      version: zod.int(),
    }),
  ),
});

/**
 * @summary Create Note
 */
export const createNoteBodyBodyDefault = ``;
export const createNoteBodyTagsDefault = ``;
export const createNoteBodyTagsMax = 500;

export const createNoteBodyTitleMax = 200;

export const CreateNoteBody = zod
  .object({
    body: zod.string().default(createNoteBodyBodyDefault),
    tags: zod
      .string()
      .max(createNoteBodyTagsMax)
      .default(createNoteBodyTagsDefault),
    title: zod.string().min(1).max(createNoteBodyTitleMax),
  })
  .describe("Create (POST) and full update (PUT).");

export const createNoteResponseTitleMax = 200;

export const CreateNoteResponse = zod.object({
  body: zod.string(),
  created: zod.iso.datetime({ offset: true }),
  id: zod.uuid(),
  modified: zod.iso.datetime({ offset: true }),
  tags: zod.string().describe("Comma-separated, normalised on write"),
  title: zod.string().max(createNoteResponseTitleMax),
  version: zod.int(),
});

/**
 * Join several notes into a new one, with an edge to the current version of each source.
 *
 * Registered before `/notes/{note_id}` so "merge" is not read as an id.
 * @summary Merge Notes
 */
export const mergeNotesBodyNoteIdsMin = 2;
export const mergeNotesBodyNoteIdsMax = 20;

export const mergeNotesBodyTitleMax = 200;

export const MergeNotesBody = zod
  .object({
    note_ids: zod
      .array(zod.uuid())
      .min(mergeNotesBodyNoteIdsMin)
      .max(mergeNotesBodyNoteIdsMax),
    title: zod.string().min(1).max(mergeNotesBodyTitleMax),
  })
  .describe("Join several notes into a new one (`POST \/api\/notes\/merge`).");

export const mergeNotesResponseTitleMax = 200;

export const MergeNotesResponse = zod.object({
  body: zod.string(),
  created: zod.iso.datetime({ offset: true }),
  id: zod.uuid(),
  modified: zod.iso.datetime({ offset: true }),
  tags: zod.string().describe("Comma-separated, normalised on write"),
  title: zod.string().max(mergeNotesResponseTitleMax),
  version: zod.int(),
});

/**
 * @summary Delete Note
 */
export const DeleteNoteParams = zod.object({
  note_id: zod.uuid(),
});

export const DeleteNoteResponse = zod.void();

/**
 * @summary Get Note
 */
export const GetNoteParams = zod.object({
  note_id: zod.uuid(),
});

export const getNoteResponseTitleMax = 200;

export const GetNoteResponse = zod.object({
  body: zod.string(),
  created: zod.iso.datetime({ offset: true }),
  id: zod.uuid(),
  modified: zod.iso.datetime({ offset: true }),
  tags: zod.string().describe("Comma-separated, normalised on write"),
  title: zod.string().max(getNoteResponseTitleMax),
  version: zod.int(),
});

/**
 * @summary Patch Note
 */
export const PatchNoteParams = zod.object({
  note_id: zod.uuid(),
});

export const patchNoteBodyTagsOneMax = 500;

export const patchNoteBodyTitleOneMax = 200;

export const PatchNoteBody = zod
  .object({
    body: zod.union([zod.string(), zod.null()]).optional(),
    tags: zod
      .union([zod.string().max(patchNoteBodyTagsOneMax), zod.null()])
      .optional(),
    title: zod
      .union([zod.string().min(1).max(patchNoteBodyTitleOneMax), zod.null()])
      .optional(),
  })
  .describe("Partial update (PATCH): only the fields that are present change.");

export const patchNoteResponseTitleMax = 200;

export const PatchNoteResponse = zod.object({
  body: zod.string(),
  created: zod.iso.datetime({ offset: true }),
  id: zod.uuid(),
  modified: zod.iso.datetime({ offset: true }),
  tags: zod.string().describe("Comma-separated, normalised on write"),
  title: zod.string().max(patchNoteResponseTitleMax),
  version: zod.int(),
});

/**
 * @summary Update Note
 */
export const UpdateNoteParams = zod.object({
  note_id: zod.uuid(),
});

export const updateNoteBodyBodyDefault = ``;
export const updateNoteBodyTagsDefault = ``;
export const updateNoteBodyTagsMax = 500;

export const updateNoteBodyTitleMax = 200;

export const UpdateNoteBody = zod
  .object({
    body: zod.string().default(updateNoteBodyBodyDefault),
    tags: zod
      .string()
      .max(updateNoteBodyTagsMax)
      .default(updateNoteBodyTagsDefault),
    title: zod.string().min(1).max(updateNoteBodyTitleMax),
  })
  .describe("Create (POST) and full update (PUT).");

export const updateNoteResponseTitleMax = 200;

export const UpdateNoteResponse = zod.object({
  body: zod.string(),
  created: zod.iso.datetime({ offset: true }),
  id: zod.uuid(),
  modified: zod.iso.datetime({ offset: true }),
  tags: zod.string().describe("Comma-separated, normalised on write"),
  title: zod.string().max(updateNoteResponseTitleMax),
  version: zod.int(),
});
