/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */

import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";
import { customFetch } from "../../lib/custom-fetch";
import type { AddIn, CountIn, StreamTaskEventsParams, TaskOut } from "../model";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getRunAddUrl = () => {
  return `/api/tasks/add`;
};

/**
 * Instant task: a + b.
 * @summary Run Add
 */
export const runAdd = async (
  addIn: AddIn,
  options?: Parameters<typeof customFetch>[1],
): Promise<TaskOut> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
  return customFetch<TaskOut>(getRunAddUrl(), {
    ...options,
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...getHeaders(options?.headers),
    },
    body: JSON.stringify(addIn),
  });
};

export const getRunAddMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof runAdd>>,
    TError,
    RunAddMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof runAdd>>,
  TError,
  RunAddMutationVariables,
  TContext
> => {
  const mutationKey = ["runAdd"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof runAdd>>,
    RunAddMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return runAdd(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RunAddMutationResult = NonNullable<
  Awaited<ReturnType<typeof runAdd>>
>;
export type RunAddMutationBody = AddIn;
export type RunAddMutationError = unknown;
export type RunAddMutationVariables = { data: AddIn };

/**
 * @summary Run Add
 */
export const useRunAdd = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof runAdd>>,
    TError,
    RunAddMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof runAdd>>,
  TError,
  RunAddMutationVariables,
  TContext
> => {
  return useMutation(getRunAddMutationOptions(options));
};
export const getRunCountUrl = () => {
  return `/api/tasks/count`;
};

/**
 * Slow task that reports PROGRESS (n steps of `delay` seconds).
 * @summary Run Count
 */
export const runCount = async (
  countIn: CountIn,
  options?: Parameters<typeof customFetch>[1],
): Promise<TaskOut> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
  return customFetch<TaskOut>(getRunCountUrl(), {
    ...options,
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...getHeaders(options?.headers),
    },
    body: JSON.stringify(countIn),
  });
};

export const getRunCountMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof runCount>>,
    TError,
    RunCountMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof runCount>>,
  TError,
  RunCountMutationVariables,
  TContext
> => {
  const mutationKey = ["runCount"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof runCount>>,
    RunCountMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return runCount(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RunCountMutationResult = NonNullable<
  Awaited<ReturnType<typeof runCount>>
>;
export type RunCountMutationBody = CountIn;
export type RunCountMutationError = unknown;
export type RunCountMutationVariables = { data: CountIn };

/**
 * @summary Run Count
 */
export const useRunCount = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof runCount>>,
    TError,
    RunCountMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof runCount>>,
  TError,
  RunCountMutationVariables,
  TContext
> => {
  return useMutation(getRunCountMutationOptions(options));
};
export const getRunDatasetSummaryUrl = () => {
  return `/api/tasks/dataset-summary`;
};

/**
 * Task that reads the database (the caller's dataset and row counts) — a `tenant_task`:
 * the worker runs it inside the caller's tenant context.
 * @summary Run Dataset Summary
 */
export const runDatasetSummary = async (
  options?: Parameters<typeof customFetch>[1],
): Promise<TaskOut> => {
  return customFetch<TaskOut>(getRunDatasetSummaryUrl(), {
    ...options,
    method: "POST",
  });
};

export const getRunDatasetSummaryMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof runDatasetSummary>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof runDatasetSummary>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["runDatasetSummary"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof runDatasetSummary>>,
    void
  > = () => {
    return runDatasetSummary(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RunDatasetSummaryMutationResult = NonNullable<
  Awaited<ReturnType<typeof runDatasetSummary>>
>;

export type RunDatasetSummaryMutationError = unknown;

/**
 * @summary Run Dataset Summary
 */
export const useRunDatasetSummary = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof runDatasetSummary>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof runDatasetSummary>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getRunDatasetSummaryMutationOptions(options));
};
export const getRunFailUrl = () => {
  return `/api/tasks/fail`;
};

/**
 * Task that raises, to see FAILURE handling end to end.
 * @summary Run Fail
 */
export const runFail = async (
  options?: Parameters<typeof customFetch>[1],
): Promise<TaskOut> => {
  return customFetch<TaskOut>(getRunFailUrl(), {
    ...options,
    method: "POST",
  });
};

export const getRunFailMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof runFail>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof runFail>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["runFail"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof runFail>>,
    void
  > = () => {
    return runFail(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RunFailMutationResult = NonNullable<
  Awaited<ReturnType<typeof runFail>>
>;

export type RunFailMutationError = unknown;

/**
 * @summary Run Fail
 */
export const useRunFail = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof runFail>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof runFail>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getRunFailMutationOptions(options));
};
export const getGetTaskUrl = (taskId: string) => {
  return `/api/tasks/${taskId}`;
};

/**
 * @summary Get Task
 */
export const getTask = async (
  taskId: string,
  options?: Parameters<typeof customFetch>[1],
): Promise<TaskOut> => {
  return customFetch<TaskOut>(getGetTaskUrl(taskId), {
    ...options,
    method: "GET",
  });
};

export const getGetTaskQueryKey = (taskId: string) => {
  return [`/api/tasks/${taskId}`] as const;
};

export const getGetTaskQueryOptions = <
  TData = Awaited<ReturnType<typeof getTask>>,
  TError = unknown,
>(
  taskId: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getTask>>, TError, TData>;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetTaskQueryKey(taskId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTask>>> = ({
    signal,
  }) => getTask(taskId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: taskId !== null && taskId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getTask>>, TError, TData> & {
    queryKey: QueryKey;
  };
};

export type GetTaskQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTask>>
>;
export type GetTaskQueryError = unknown;

/**
 * @summary Get Task
 */

export function useGetTask<
  TData = Awaited<ReturnType<typeof getTask>>,
  TError = unknown,
>(
  taskId: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getTask>>, TError, TData>;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetTaskQueryOptions(taskId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getStreamTaskEventsUrl = (
  taskId: string,
  params: StreamTaskEventsParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/tasks/${taskId}/events?${stringifiedParams}`
    : `/api/tasks/${taskId}/events`;
};

/**
 * Server-Sent Events with the task's status: one `status` event now and one per change,
 * then the connection closes once the task is ready (text/event-stream, not part of the JSON
 * contract — use `TaskOut.stream_url`, which carries the signature).
 *
 * The stream also closes after `tasks.WATCH_TIMEOUT`; EventSource reconnects on its own.
 * @summary Stream Task Events
 */
export const streamTaskEvents = async (
  taskId: string,
  params: StreamTaskEventsParams,
  options?: Parameters<typeof customFetch>[1],
): Promise<void> => {
  return customFetch<void>(getStreamTaskEventsUrl(taskId, params), {
    ...options,
    method: "GET",
  });
};

export const getStreamTaskEventsQueryKey = (
  taskId: string,
  params?: StreamTaskEventsParams,
) => {
  return [`/api/tasks/${taskId}/events`, ...(params ? [params] : [])] as const;
};

export const getStreamTaskEventsQueryOptions = <
  TData = Awaited<ReturnType<typeof streamTaskEvents>>,
  TError = unknown,
>(
  taskId: string,
  params: StreamTaskEventsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof streamTaskEvents>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getStreamTaskEventsQueryKey(taskId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof streamTaskEvents>>
  > = ({ signal }) =>
    streamTaskEvents(taskId, params, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: taskId !== null && taskId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof streamTaskEvents>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type StreamTaskEventsQueryResult = NonNullable<
  Awaited<ReturnType<typeof streamTaskEvents>>
>;
export type StreamTaskEventsQueryError = unknown;

/**
 * @summary Stream Task Events
 */

export function useStreamTaskEvents<
  TData = Awaited<ReturnType<typeof streamTaskEvents>>,
  TError = unknown,
>(
  taskId: string,
  params: StreamTaskEventsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof streamTaskEvents>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getStreamTaskEventsQueryOptions(taskId, params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return withQueryKey(query, queryOptions.queryKey);
}
