"""Row-level security on every owned table: the database-side tenant guarantee.

Policies are generated from the model registry (every concrete `OwnedModel`), not hand-written,
and applied by `manage.py rls_sync` after every `migrate` (`./scripts/migrate.sh`,
`docker/entrypoint.sh`). `rls_sync --check` / `verify()` is the deploy gate; the readiness probe
(`apps/core/health.py`) and the `tenant.E003` system check report drift as well.

    CREATE POLICY tenant_isolation ON <table> AS PERMISSIVE FOR ALL TO app_user
        USING (owner_id = NULLIF(current_setting('app.user_id', true), '')::uuid)
        WITH CHECK (owner_id = NULLIF(current_setting('app.user_id', true), '')::uuid);

`NULLIF(…, '')`: the context is cleared by setting the variable to the empty string, and
`''::uuid` would raise. NULLIF turns it into NULL, the comparison is NULL, no row is visible or
writable — the policy fails closed. Never add `OR current_setting(...) IS NULL` for convenience:
that is a permanent, silent backdoor.

`verify()` compares the *expression* Postgres has stored, not just its presence: a policy that
was altered to `USING (true)`, or one left over from an earlier `TENANT_GUC` name, is drift and
must fail the gate exactly like a missing one.

Roles (docker/postgres/10-roles.sh): the policies target `app_user`, the runtime role. A table's
owner (`app_migrator`) and `BYPASSRLS` roles (`app_admin`) are not subject to them, which is
exactly why the web process must never connect as either — `connection_bypasses_rls()` tells,
and `require_cross_tenant_access()` is the assertion for tooling that needs the opposite.
"""

import re
from dataclasses import dataclass

from django.apps import apps
from django.db import connection
from django.db.models import Model

from apps.core.db import guc_name
from apps.core.models import OWNER_COLUMN, OwnedModel

POLICY = "tenant_isolation"
APP_ROLE = "app_user"
ADMIN_ROLE = "app_admin"
MIGRATOR_ROLE = "app_migrator"
WRITE_PRIVILEGES = ("SELECT", "INSERT", "UPDATE", "DELETE")

_ENABLE = "ALTER TABLE {table} ENABLE ROW LEVEL SECURITY"
_DROP = "DROP POLICY IF EXISTS {policy} ON {table}"
_CREATE = """
CREATE POLICY {policy} ON {table}
    AS PERMISSIVE FOR ALL TO {role}
    USING (owner_id = NULLIF(current_setting('{guc}', true), '')::uuid)
    WITH CHECK (owner_id = NULLIF(current_setting('{guc}', true), '')::uuid)
"""
# Everything the app touches, not only owned tables: sessions, users, migrations, ... — and
# independent of who created the table (default privileges are per creating role).
_GRANTS = (
    "GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO {roles}",
    "GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO {roles}",
)


class CrossTenantAccessRequired(Exception):
    """The connection is subject to row-level security, but the caller needs every tenant."""


def tenant_models() -> list[type[OwnedModel]]:
    """Every concrete model that inherits `OwnedModel`, in a stable order.

    This is the *tenant tooling* set — what a tenant owns, for extraction and erasure. The set
    of tables that need a policy is wider (`isolated_models()`): an event table holds the same
    rows one version older, and it is not an `OwnedModel`.
    """
    models = [
        model
        for model in apps.get_models()
        if issubclass(model, OwnedModel) and not model._meta.abstract
    ]
    return sorted(models, key=lambda model: model._meta.db_table)


def tenant_tables() -> list[str]:
    return [model._meta.db_table for model in tenant_models()]


def isolated_models() -> list[type[Model]]:
    """Every concrete table the policy applies to: anything with an `owner_id` column.

    Deliberately a property of the table, not of a base class. Owned models are the obvious
    members, but the event tables generated by `apps/core/history.py` mirror `owner_id` while
    inheriting `pghistory.models.Event`, and `Lineage` carries one without being versioned at
    all. All three hold one tenant's data, so all three fail closed without a context; a rule
    keyed on `OwnedModel` would have silently let history and lineage escape (they are readable
    by `app_user` like any other table, RLS is what stops that).
    """
    models = [
        model
        for model in apps.get_models()
        if not model._meta.abstract
        and any(field.attname == OWNER_COLUMN for field in model._meta.fields)
    ]
    return sorted(models, key=lambda model: model._meta.db_table)


def isolated_tables() -> list[str]:
    return [model._meta.db_table for model in isolated_models()]


def writable_tables() -> list[str]:
    """Every table the runtime role has to be able to write at all.

    The policies decide *which rows* `app_user` sees; the grants decide whether it may touch the
    table in the first place, and a table created later starts with none — the initial
    `GRANT ... ON ALL TABLES` in `docker/postgres/10-roles.sh` is a snapshot of what existed
    then. Checking the whole registry, not just the isolated tables, is what makes `sync()`
    notice a new shared one (`core_commandrun` was the case that found this).
    """
    return sorted({model._meta.db_table for model in apps.get_models() if not model._meta.abstract})


def expected_expression() -> str:
    """The policy expression as Postgres renders it back (`pg_get_expr`).

    Pinned in code so `verify()` can compare what the database actually stores against what
    `_CREATE` generates; `test_tenancy.py` checks this string against a live policy, so a
    Postgres release that renders it differently breaks a test, never production.
    """
    return f"(owner_id = (NULLIF(current_setting('{guc_name()}'::text, true), ''::text))::uuid)"


def _normalize(expression: str) -> str:
    return re.sub(r"\s+", " ", expression).strip()


@dataclass(frozen=True)
class TableState:
    exists: bool = False
    rls_enabled: bool = False
    has_policy: bool = False
    policy_for_app_role: bool = False
    using: str = ""
    with_check: str = ""
    app_role_can_write: bool = False

    def policy_matches(self, expected: str) -> bool:
        return _normalize(self.using) == expected and _normalize(self.with_check) == expected

    def is_healthy(self, expected: str) -> bool:
        return (
            self.exists
            and self.rls_enabled
            and self.has_policy
            and self.policy_for_app_role
            and self.policy_matches(expected)
            and self.app_role_can_write
        )


def _states(tables: list[str]) -> dict[str, TableState]:
    # has_table_privilege() with a comma-separated list is OR, not AND ("true if any of the
    # listed privileges is held") — so each privilege gets its own call and they are ANDed here.
    privileges = " AND ".join(f"has_table_privilege(%s, c.oid, '{p}')" for p in WRITE_PRIVILEGES)
    with connection.cursor() as cursor:
        cursor.execute(
            f"""
            SELECT c.relname,
                   c.relrowsecurity,
                   p.polname IS NOT NULL,
                   coalesce(
                       %s = ANY(SELECT rolname FROM pg_roles WHERE oid = ANY(p.polroles)), false
                   ),
                   coalesce(pg_get_expr(p.polqual, p.polrelid), ''),
                   coalesce(pg_get_expr(p.polwithcheck, p.polrelid), ''),
                   {privileges}
            FROM pg_class c
            JOIN pg_namespace n ON n.oid = c.relnamespace
            LEFT JOIN pg_policy p ON p.polrelid = c.oid AND p.polname = %s
            WHERE n.nspname = 'public' AND c.relkind = 'r' AND c.relname = ANY(%s)
            """,
            [APP_ROLE, *([APP_ROLE] * len(WRITE_PRIVILEGES)), POLICY, tables],
        )
        rows = cursor.fetchall()
    found = {
        row[0]: TableState(
            exists=True,
            rls_enabled=bool(row[1]),
            has_policy=bool(row[2]),
            policy_for_app_role=bool(row[3]),
            using=str(row[4]),
            with_check=str(row[5]),
            app_role_can_write=bool(row[6]),
        )
        for row in rows
    }
    return {table: found.get(table, TableState()) for table in tables}


def sync(*, tables: list[str] | None = None) -> list[str]:
    """Bring every owned table that exists to the policy above; returns the tables it changed.

    Idempotent *and* quiet: a table that already carries the right policy is not touched, so
    the `rls_sync` on every container start takes no locks on a healthy database. Must run as
    the table owner (DB_ROLE=migrator).

    Tables of models whose migration has not been applied yet are skipped — `migrate` first,
    then `sync()` again (which is what ./scripts/migrate.sh and the entrypoint do).
    """
    tables = isolated_tables() if tables is None else tables
    expected = expected_expression()
    quote = connection.ops.quote_name
    state = _states(tables)
    changed = []
    with connection.cursor() as cursor:
        for table, current in state.items():
            if not current.exists or current.is_healthy(expected):
                continue
            if not current.rls_enabled:
                cursor.execute(_ENABLE.format(table=quote(table)))
            if not (current.policy_for_app_role and current.policy_matches(expected)):
                cursor.execute(_DROP.format(policy=POLICY, table=quote(table)))
                cursor.execute(
                    _CREATE.format(policy=POLICY, table=quote(table), role=APP_ROLE, guc=guc_name())
                )
            changed.append(table)
        # Grants are per table, and `_GRANTS` covers all of them at once, so the question is
        # only whether *any* table is missing them — including tables with no policy, which
        # `state` does not cover. A SELECT, so a healthy database still sees no DDL.
        if any(not s.app_role_can_write for s in _states(writable_tables()).values() if s.exists):
            for grant in _GRANTS:
                cursor.execute(grant.format(roles=f"{APP_ROLE}, {ADMIN_ROLE}"))
    return changed


def verify(*, tables: list[str] | None = None) -> list[str]:
    """Human-readable drift, one entry per problem; empty when every owned table is protected.

    Checks the whole invariant: table exists, RLS enabled, a policy for `app_user` whose USING
    and WITH CHECK expressions are the generated ones, and all four write privileges granted.
    """
    tables = isolated_tables() if tables is None else tables
    expected = expected_expression()
    problems = []
    for table, state in _states(tables).items():
        if not state.exists:
            problems.append(f"{table}: table missing (unapplied migration?)")
            continue
        if not state.rls_enabled:
            problems.append(f"{table}: row-level security not enabled")
        if not state.has_policy:
            problems.append(f"{table}: policy {POLICY!r} missing")
            continue
        if not state.policy_for_app_role:
            problems.append(f"{table}: policy {POLICY!r} does not apply to role {APP_ROLE}")
        if not state.using or not state.with_check:
            problems.append(f"{table}: policy {POLICY!r} needs both USING and WITH CHECK")
        elif not state.policy_matches(expected):
            problems.append(
                f"{table}: policy {POLICY!r} does not isolate tenants — "
                f"USING {_normalize(state.using)}, WITH CHECK {_normalize(state.with_check)}, "
                f"expected {expected}"
            )
        if not state.app_role_can_write:
            problems.append(
                f"{table}: role {APP_ROLE} lacks {'/'.join(WRITE_PRIVILEGES)} on the table"
            )
    return problems


def current_role() -> str:
    with connection.cursor() as cursor:
        cursor.execute("SELECT current_user")
        row = cursor.fetchone()
    return str(row[0]) if row else ""


def connection_bypasses_rls() -> str | None:
    """Why the current connection's role is *not* subject to the policies, or None if it is.

    Superusers, `BYPASSRLS` roles and table owners see everything regardless of any policy.
    The web process and the workers must run with `None` here; backups need a reason.
    """
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT current_user, rolsuper, rolbypassrls FROM pg_roles WHERE rolname = current_user"
        )
        row = cursor.fetchone()
        if row is None:  # pragma: no cover - current_user always exists
            return None
        role, superuser, bypass = str(row[0]), bool(row[1]), bool(row[2])
        cursor.execute(
            "SELECT count(*) FROM pg_tables WHERE schemaname = 'public' "
            "AND tablename = ANY(%s) AND tableowner = current_user",
            [tenant_tables()],
        )
        owned = cursor.fetchone()
    if superuser:
        return f"role {role} is a superuser"
    if bypass:
        return f"role {role} has BYPASSRLS"
    if owned is not None and int(owned[0]) > 0:
        return f"role {role} owns the tables"
    return None


def require_cross_tenant_access() -> None:
    """Assert that this connection sees *all* tenants — for tooling that must (dumps, erasure).

    As the runtime role such a job would silently work on one tenant's rows (or none at all),
    which is worse than not running: it would write a partial backup or leave data behind.
    """
    if connection_bypasses_rls() is None:
        raise CrossTenantAccessRequired(
            f"connected as {current_role()}, which only sees one tenant's rows; "
            "run with DB_ROLE=migrator (./scripts/backup.sh) or DB_ROLE=admin"
        )
