# Generated by Django 5.2.6 on 2025-11-06 15:48

import config.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationPoint',
            fields=[
                ('id', models.CharField(default=config.models.id_gen, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('was_interpolated', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='TravelDistance',
            fields=[
                ('id', models.CharField(default=config.models.id_gen, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('distance_m', models.FloatField()),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distances_from', to='locations.locationpoint')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distances_to', to='locations.locationpoint')),
            ],
            options={
                'verbose_name': 'Travel Distance',
                'verbose_name_plural': 'Travel Distances',
                'ordering': ['-created'],
            },
        ),
    ]
