/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * @summary List Api Tokens
 */
export const listApiTokensResponseNameMax = 255;

export const listApiTokensResponseTokenMax = 64;

export const ListApiTokensResponseItem = zod.object({
  created: zod.iso.datetime({ offset: true }),
  id: zod.uuid(),
  last_used: zod.union([zod.iso.datetime({ offset: true }), zod.null()]),
  name: zod
    .string()
    .max(listApiTokensResponseNameMax)
    .describe("What the token is used for"),
  token: zod.string().max(listApiTokensResponseTokenMax).optional(),
});
export const ListApiTokensResponse = zod.array(ListApiTokensResponseItem);

/**
 * @summary Create Api Token
 */
export const createApiTokenBodyNameMax = 255;

export const CreateApiTokenBody = zod.object({
  name: zod.string().min(1).max(createApiTokenBodyNameMax),
});

export const createApiTokenResponseNameMax = 255;

export const createApiTokenResponseTokenMax = 64;

export const CreateApiTokenResponse = zod.object({
  created: zod.iso.datetime({ offset: true }),
  id: zod.uuid(),
  last_used: zod.union([zod.iso.datetime({ offset: true }), zod.null()]),
  name: zod
    .string()
    .max(createApiTokenResponseNameMax)
    .describe("What the token is used for"),
  token: zod.string().max(createApiTokenResponseTokenMax).optional(),
});

/**
 * @summary Revoke Api Token
 */
export const RevokeApiTokenParams = zod.object({
  token_id: zod.uuid(),
});

export const RevokeApiTokenResponse = zod.void();

/**
 * @summary Login
 */
export const LoginBody = zod.object({
  password: zod.string(),
  username: zod.string(),
});

export const LoginResponse = zod
  .object({
    access_token: zod.string(),
    refresh_token: zod.string(),
  })
  .describe(
    "Send `access_token` as `Authorization: Bearer …`; it expires after\nACCESS_TOKEN_LIFETIME_MINUTES. Then POST `refresh_token` to \/auth\/refresh for a new pair\n(the refresh token is single-use) — or to \/auth\/logout to end the session.",
  );

/**
 * End the session: the refresh token stops working (the access token expires by itself).
 *
 * Public for the same reason as /auth/refresh; always 204, even for a token that is gone.
 * @summary Logout
 */
export const LogoutBody = zod.object({
  refresh_token: zod.string(),
});

export const LogoutResponse = zod.void();

/**
 * @summary Get Current User
 */
export const GetCurrentUserResponse = zod.object({
  email: zod.string(),
  first_name: zod.string(),
  id: zod.uuid(),
  is_staff: zod.boolean(),
  last_name: zod.string(),
  username: zod.string(),
});

/**
 * Trade a refresh token for a new access + refresh pair (the old refresh token is revoked).
 *
 * Public: the access token is usually expired by the time this is called; the refresh token
 * in the body is the credential.
 * @summary Refresh Token
 */
export const RefreshTokenBody = zod.object({
  refresh_token: zod.string(),
});

export const RefreshTokenResponse = zod
  .object({
    access_token: zod.string(),
    refresh_token: zod.string(),
  })
  .describe(
    "Send `access_token` as `Authorization: Bearer …`; it expires after\nACCESS_TOKEN_LIFETIME_MINUTES. Then POST `refresh_token` to \/auth\/refresh for a new pair\n(the refresh token is single-use) — or to \/auth\/logout to end the session.",
  );

/**
 * Self-service sign-up; only available when `REGISTRATION_OPEN=true`.
 * @summary Register
 */
export const registerBodyEmailDefault = ``;
export const registerBodyFirstNameDefault = ``;
export const registerBodyLastNameDefault = ``;
export const registerBodyPasswordMin = 8;

export const registerBodyUsernameMax = 150;

export const RegisterBody = zod.object({
  email: zod.string().default(registerBodyEmailDefault),
  first_name: zod.string().default(registerBodyFirstNameDefault),
  last_name: zod.string().default(registerBodyLastNameDefault),
  password: zod.string().min(registerBodyPasswordMin),
  username: zod.string().min(1).max(registerBodyUsernameMax),
});

export const RegisterResponse = zod
  .object({
    access_token: zod.string(),
    refresh_token: zod.string(),
  })
  .describe(
    "Send `access_token` as `Authorization: Bearer …`; it expires after\nACCESS_TOKEN_LIFETIME_MINUTES. Then POST `refresh_token` to \/auth\/refresh for a new pair\n(the refresh token is single-use) — or to \/auth\/logout to end the session.",
  );
