/**
 * Generated by orval 🍺
 * Do not edit manually.
 * dx API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * @summary List Api Tokens
 */
export const listApiTokensResponseNameMax = 255;

export const listApiTokensResponseTokenMax = 64;

export const ListApiTokensResponseItem = zod.object({
  created: zod.iso.datetime({ offset: true }),
  id: zod.uuid(),
  last_used: zod.union([zod.iso.datetime({ offset: true }), zod.null()]),
  name: zod
    .string()
    .max(listApiTokensResponseNameMax)
    .describe("What the token is used for"),
  token: zod.string().max(listApiTokensResponseTokenMax).optional(),
});
export const ListApiTokensResponse = zod.array(ListApiTokensResponseItem);

/**
 * @summary Create Api Token
 */
export const createApiTokenBodyNameMax = 255;

export const CreateApiTokenBody = zod.object({
  name: zod.string().min(1).max(createApiTokenBodyNameMax),
});

export const createApiTokenResponseNameMax = 255;

export const createApiTokenResponseTokenMax = 64;

export const CreateApiTokenResponse = zod.object({
  created: zod.iso.datetime({ offset: true }),
  id: zod.uuid(),
  last_used: zod.union([zod.iso.datetime({ offset: true }), zod.null()]),
  name: zod
    .string()
    .max(createApiTokenResponseNameMax)
    .describe("What the token is used for"),
  token: zod.string().max(createApiTokenResponseTokenMax).optional(),
});

/**
 * @summary Revoke Api Token
 */
export const RevokeApiTokenParams = zod.object({
  token_id: zod.uuid(),
});

export const RevokeApiTokenResponse = zod.void();

/**
 * @summary Login
 */
export const LoginBody = zod.object({
  password: zod.string(),
  username: zod.string(),
});

export const LoginResponse = zod
  .object({
    access_token: zod.string(),
  })
  .describe("Send as `Authorization: Bearer <access_token>`.");

/**
 * @summary Get Current User
 */
export const GetCurrentUserResponse = zod.object({
  email: zod.string(),
  first_name: zod.string(),
  id: zod.uuid(),
  is_staff: zod.boolean(),
  last_name: zod.string(),
  username: zod.string(),
});

/**
 * Issue a fresh access token for the caller (call before the current one expires).
 * @summary Refresh Token
 */
export const RefreshTokenResponse = zod
  .object({
    access_token: zod.string(),
  })
  .describe("Send as `Authorization: Bearer <access_token>`.");

/**
 * Self-service sign-up; only available when `REGISTRATION_OPEN=true`.
 * @summary Register
 */
export const registerBodyEmailDefault = ``;
export const registerBodyFirstNameDefault = ``;
export const registerBodyLastNameDefault = ``;
export const registerBodyPasswordMin = 8;

export const registerBodyUsernameMax = 150;

export const RegisterBody = zod.object({
  email: zod.string().default(registerBodyEmailDefault),
  first_name: zod.string().default(registerBodyFirstNameDefault),
  last_name: zod.string().default(registerBodyLastNameDefault),
  password: zod.string().min(registerBodyPasswordMin),
  username: zod.string().min(1).max(registerBodyUsernameMax),
});

export const RegisterResponse = zod
  .object({
    access_token: zod.string(),
  })
  .describe("Send as `Authorization: Bearer <access_token>`.");
